// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.CommandLine;
using System.Text.Json;
using Azure.Functions.Cli.Common;
using Azure.Functions.Cli.Workloads;

namespace Azure.Functions.Cli.Workload.Dotnet;

/// <summary>
/// Handles 'func init' for .NET projects. Installs the Worker project template
/// pack and delegates to 'dotnet new func' for project scaffolding.
/// </summary>
public class DotnetProjectInitializer : IProjectInitializer
{
    private readonly IDotnetCliRunner _dotnetCli;

    /// <summary>
    /// Pinned fallback version used when NuGet is unreachable (offline mode).
    /// Update this when a new stable template pack is released.
    /// </summary>
    internal const string ProjectTemplatePackageId = "Microsoft.Azure.Functions.Worker.ProjectTemplates";
    internal const string DefaultTargetFramework = "net10.0";

    public static readonly Option<string> TargetFrameworkOption = new("--target-framework", "-tfm")
    {
        Description = $"The target framework for the project (default: {DefaultTargetFramework})",
        DefaultValueFactory = _ => DefaultTargetFramework
    };

    public DotnetProjectInitializer(IDotnetCliRunner dotnetCli)
    {
        _dotnetCli = dotnetCli;
    }

    public string WorkerRuntime => "dotnet";

    public IReadOnlyList<string> SupportedLanguages => ["C#", "F#"];

    public IReadOnlyList<Option> GetInitOptions() => [TargetFrameworkOption];

    public bool CanHandle(string workerRuntime) =>
        workerRuntime.Equals("dotnet", StringComparison.OrdinalIgnoreCase)
        || workerRuntime.Equals("dotnet-isolated", StringComparison.OrdinalIgnoreCase);

    public async Task InitializeAsync(ProjectInitContext context, ParseResult parseResult, CancellationToken cancellationToken = default)
    {
        var targetFramework = parseResult.GetValue(TargetFrameworkOption) ?? DefaultTargetFramework;
        var language = context.Language ?? "C#";
        var projectName = context.ProjectName ?? Path.GetFileName(context.ProjectPath);

        if (context.Force)
        {
            CleanConflictingDotnetFiles(context.ProjectPath, language);
        }

        await EnsureTemplatePackInstalledAsync(cancellationToken);

        var args = $"new func --name \"{projectName}\" --output \"{context.ProjectPath}\" --language \"{language}\" --Framework {targetFramework}";
        if (context.Force)
        {
            args += " --force";
        }

        var result = await _dotnetCli.RunAsync(args, cancellationToken: cancellationToken);
        if (!result.IsSuccess)
        {
            throw new GracefulException(
                "Failed to create .NET Functions project.",
                result.StandardError.Trim());
        }

        await WriteLocalSettingsAsync(context.ProjectPath, cancellationToken);
        WriteGitIgnore(context.ProjectPath);
    }

    /// <summary>
    /// Removes project files from the opposite .NET language so that
    /// reinitializing (e.g., C# → F#) doesn't leave stale artifacts.
    /// </summary>
    private static void CleanConflictingDotnetFiles(string projectPath, string language)
    {
        // Remove the opposite project file type
        var conflictingExtension = language.Equals("F#", StringComparison.OrdinalIgnoreCase)
            ? "*.csproj"
            : "*.fsproj";

        foreach (var file in Directory.EnumerateFiles(projectPath, conflictingExtension))
        {
            File.Delete(file);
        }

        // Remove source files that will be regenerated by dotnet new
        foreach (var pattern in new[] { "*.cs", "*.fs" })
        {
            foreach (var file in Directory.EnumerateFiles(projectPath, pattern))
            {
                File.Delete(file);
            }
        }
    }

    private async Task EnsureTemplatePackInstalledAsync(CancellationToken cancellationToken)
    {
        var bundledVersion = BundledTemplateVersions.ProjectTemplatesVersion;
        var version = await NuGetTemplateResolver.ResolveVersionAsync(
            ProjectTemplatePackageId, bundledVersion, cancellationToken);

        if (await TryInstallTemplatePackAsync(ProjectTemplatePackageId, version, cancellationToken))
        {
            return;
        }

        // If the resolved version failed and it differs from bundled, try the bundled version
        if (!version.Equals(bundledVersion, StringComparison.OrdinalIgnoreCase)
            && await TryInstallTemplatePackAsync(ProjectTemplatePackageId, bundledVersion, cancellationToken))
        {
            return;
        }

        // Last resort: try installing from the bundled .nupkg shipped with the workload
        if (await TryInstallFromBundledNupkgAsync(ProjectTemplatePackageId, bundledVersion, cancellationToken))
        {
            return;
        }

        throw new GracefulException(
            $"Failed to install template pack '{ProjectTemplatePackageId}'.",
            $"Tried version '{version}' from NuGet and bundled version '{bundledVersion}'. " +
            "Check your internet connection or reinstall the dotnet workload.");
    }

    private static async Task WriteLocalSettingsAsync(string projectPath, CancellationToken cancellationToken)
    {
        var settingsPath = Path.Combine(projectPath, "local.settings.json");
        if (File.Exists(settingsPath))
        {
            return;
        }

        var settings = new
        {
            IsEncrypted = false,
            Values = new Dictionary<string, string>
            {
                ["AzureWebJobsStorage"] = "UseDevelopmentStorage=true",
                ["FUNCTIONS_WORKER_RUNTIME"] = "dotnet-isolated"
            }
        };

        var json = JsonSerializer.Serialize(settings, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(settingsPath, json, cancellationToken);
    }

    private static void WriteGitIgnore(string projectPath)
    {
        var gitignorePath = Path.Combine(projectPath, ".gitignore");
        if (File.Exists(gitignorePath))
        {
            return;
        }

        File.WriteAllText(gitignorePath,
            """
            ## Azure Functions localsettings file
            local.settings.json

            ## Ignore Visual Studio / Rider / VS Code artifacts
            bin/
            obj/
            .vs/
            .idea/
            *.user

            ## Publish output
            publish/
            """);
    }

    /// <summary>
    /// Tries to install a template pack by version from NuGet.
    /// Returns true if installed or already installed.
    /// </summary>
    private async Task<bool> TryInstallTemplatePackAsync(
        string packageId, string version, CancellationToken cancellationToken)
    {
        var result = await _dotnetCli.RunAsync(
            $"new install {packageId}::{version}",
            cancellationToken: cancellationToken);

        if (result.IsSuccess)
        {
            return true;
        }

        // Already installed at this version — that's fine
        if (result.StandardError.Contains("is already installed", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return false;
    }

    /// <summary>
    /// Tries to install a template from the bundled .nupkg file shipped
    /// alongside the workload assembly (in the templates/ subdirectory).
    /// </summary>
    private async Task<bool> TryInstallFromBundledNupkgAsync(
        string packageId, string version, CancellationToken cancellationToken)
    {
        var assemblyDir = Path.GetDirectoryName(typeof(DotnetProjectInitializer).Assembly.Location);
        if (assemblyDir is null) return false;

        var nupkgPath = Path.Combine(assemblyDir, "templates",
            $"{packageId.ToLowerInvariant()}.{version}.nupkg");

        if (!File.Exists(nupkgPath)) return false;

        var result = await _dotnetCli.RunAsync(
            $"new install \"{nupkgPath}\"",
            cancellationToken: cancellationToken);

        return result.IsSuccess
            || result.StandardError.Contains("is already installed", StringComparison.OrdinalIgnoreCase);
    }
}
