apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scaledobjects.keda.k8s.io
spec:
  group: keda.k8s.io
  version: v1alpha1
  names:
    kind: ScaledObject
    plural: scaledobjects
  scope: Namespaced
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: keda
  name: keda-docker-auth
  namespace: KEDA_NAMESPACE
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsicHJvamVjdGtvcmUuYXp1cmVjci5pbyI6IHsiYXV0aCI6ICJZalV4TkdJMk1HTXROamhqWXkwMFpqRXlMV0l6TmpFdE16ZzFPRGczT0dJeU5EYzVPalJxV0RWMmExQlVVM0pWVVRrMlZVSmlWUzlDTjBOUmNrSnZTbmRVTmpKWFUzTTFWMlphZEVaaVFqZzkifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: keda
  name: keda
  namespace: KEDA_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: keda
  name: keda
  namespace: KEDA_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: keda
  namespace: KEDA_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-hpa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda
  name: keda
  namespace: KEDA_NAMESPACE
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: keda
    instance: keda-instance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda
  name: keda
  namespace: KEDA_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keda
      instance: keda-instance
  template:
    metadata:
      labels:
        name: keda
        instance: keda-instance
    spec:
      serviceAccountName: keda
      containers:
      - name: keda
        # image: "projectkore.azurecr.io/kore:master"
        image: "ahmelsayed/contcont:latest"
        imagePullPolicy: Always
        args:
        - --log-level=debug
        - /adapter
        - --secure-port=6443
        - --logtostderr=false
        - --v=2
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
      imagePullSecrets:
      - name: keda-docker-auth
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: keda
    namespace: KEDA_NAMESPACE
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: keda
    namespace: KEDA_NAMESPACE
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---