services:
  func-cli:
    build:
      context: ..  # Go up one level to repo root
      dockerfile: docker/Dockerfile
      args:
        TARGET_RUNTIME: linux-x64
    # platform: linux/amd64 # Uncomment if you are on an M1/M2 Mac AND running a x64 build
    container_name: func-cli
    image: func-cli
