// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Globalization;
using System.Text;
using Azure.Functions.Cli.Tools.TemplateGenerator.Common;
using Azure.Functions.Cli.Tools.TemplateGenerator.Model;
using Azure.Functions.Cli.Tools.TemplateGenerator.V1.Model;

namespace Azure.Functions.Cli.Tools.TemplateGenerator.V1;

internal static class BindingsEmitterV1
{
    private const string BindingsNamespace = "Azure.Functions.Cli.Bindings";

    private const string PocoHeader = """
        // <auto-generated/>
        #nullable enable

        namespace Azure.Functions.Cli.Bindings;

        """;

    public static string EmitBindingDefinition() => PocoHeader + """
        /// <summary>
        /// Represents an Azure Functions v1 binding definition (from bindings.json).
        /// </summary>
        internal sealed class BindingDefinitionV1
        {
            /// <summary>Gets the binding type (e.g. "queueTrigger").</summary>
            public required string Type { get; init; }

            /// <summary>Gets the localized display name (often a token reference).</summary>
            public required string DisplayName { get; init; }

            /// <summary>Gets the binding direction.</summary>
            public required BindingSchemaDirectionV1 Direction { get; init; }

            /// <summary>Gets whether the binding is enabled in try mode.</summary>
            public required bool EnabledInTryMode { get; init; }

            /// <summary>Gets the documentation markdown, if any.</summary>
            public string? Documentation { get; init; }

            /// <summary>Gets the binding settings (user-configurable parameters).</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingSettingV1> Settings { get; init; }

            /// <summary>Gets the related actions (cross-references to template scaffolding).</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingActionRefV1> Actions { get; init; }

            /// <summary>Gets the WebJobs extension that supplies this binding, if any.</summary>
            public BindingExtensionRefV1? Extension { get; init; }

            /// <summary>Gets dynamic UI rules that show/hide settings based on user choices.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingRuleV1> Rules { get; init; }
        }

        """;

    public static string EmitDirection() => PocoHeader + """
        /// <summary>
        /// Represents the direction of an Azure Functions v1 binding.
        /// </summary>
        internal enum BindingSchemaDirectionV1
        {
            /// <summary>Input binding.</summary>
            In,

            /// <summary>Output binding.</summary>
            Out,

            /// <summary>Trigger binding.</summary>
            Trigger,
        }

        """;

    public static string EmitSetting() => PocoHeader + """
        /// <summary>
        /// Represents a single user-configurable setting on a v1 binding.
        /// </summary>
        internal sealed class BindingSettingV1
        {
            /// <summary>Gets the setting name (used as the JSON property in function.json).</summary>
            public required string Name { get; init; }

            /// <summary>Gets the value type expected for this setting.</summary>
            public required BindingSettingValueTypeV1 Value { get; init; }

            /// <summary>Gets whether the setting is required.</summary>
            public bool? Required { get; init; }

            /// <summary>Gets the localized label (often a token reference).</summary>
            public string? Label { get; init; }

            /// <summary>Gets the localized help text (often a token reference).</summary>
            public string? Help { get; init; }

            /// <summary>Gets the default value, if any. May be a string, bool, long, or string array.</summary>
            public object? DefaultValue { get; init; }

            /// <summary>Gets the placeholder text shown in UI inputs, if any.</summary>
            public string? Placeholder { get; init; }

            /// <summary>Gets the Azure resource type this setting selects, if any (e.g. "AppSetting").</summary>
            public string? Resource { get; init; }

            /// <summary>Gets the allowed enum values when <see cref="Value"/> is <see cref="BindingSettingValueTypeV1.Enum"/> or <see cref="BindingSettingValueTypeV1.CheckBoxList"/>.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingEnumValueV1> Enum { get; init; }

            /// <summary>Gets validators applied to user input for this setting.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingValueValidatorV1> Validators { get; init; }
        }

        """;

    public static string EmitSettingValueType() => PocoHeader + """
        /// <summary>
        /// The expected value type of a v1 binding setting.
        /// </summary>
        internal enum BindingSettingValueTypeV1
        {
            /// <summary>String input.</summary>
            String,

            /// <summary>Boolean input.</summary>
            Bool,

            /// <summary>Integer input.</summary>
            Int,

            /// <summary>Single selection from <see cref="BindingSettingV1.Enum"/>.</summary>
            Enum,

            /// <summary>Multi-selection from <see cref="BindingSettingV1.Enum"/>.</summary>
            CheckBoxList,
        }

        """;

    public static string EmitValidator() => PocoHeader + """
        /// <summary>
        /// A regex validator applied to a v1 binding setting input.
        /// </summary>
        internal sealed class BindingValueValidatorV1
        {
            /// <summary>Gets the regular expression that valid input must match.</summary>
            public required string Expression { get; init; }

            /// <summary>Gets the error text shown when input does not match (often a token reference).</summary>
            public required string ErrorText { get; init; }
        }

        """;

    public static string EmitEnumValue() => PocoHeader + """
        /// <summary>
        /// A single allowed value for a v1 binding setting whose value type is enum or checkbox list.
        /// </summary>
        internal sealed class BindingEnumValueV1
        {
            /// <summary>Gets the underlying value emitted to function.json.</summary>
            public required string Value { get; init; }

            /// <summary>Gets the localized display name shown in UI (often a token reference).</summary>
            public required string Display { get; init; }
        }

        """;

    public static string EmitActionRef() => PocoHeader + """
        /// <summary>
        /// A cross-reference from a v1 binding to a template action that scaffolds it.
        /// </summary>
        internal sealed class BindingActionRefV1
        {
            /// <summary>Gets the template name.</summary>
            public required string Template { get; init; }

            /// <summary>Gets the binding name within the template.</summary>
            public required string Binding { get; init; }

            /// <summary>Gets the names of settings populated by this action.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<string> Settings { get; init; }
        }

        """;

    public static string EmitExtensionRef() => PocoHeader + """
        /// <summary>
        /// Identifies the WebJobs extension package that supplies a v1 binding.
        /// </summary>
        internal sealed class BindingExtensionRefV1
        {
            /// <summary>Gets the extension package id.</summary>
            public required string Id { get; init; }

            /// <summary>Gets the extension package version.</summary>
            public required string Version { get; init; }
        }

        """;

    public static string EmitRule() => PocoHeader + """
        /// <summary>
        /// A dynamic UI rule that shows or hides v1 binding settings based on user choices.
        /// </summary>
        internal sealed class BindingRuleV1
        {
            /// <summary>Gets the rule identifier.</summary>
            public required string Name { get; init; }

            /// <summary>Gets the rule type (e.g. "exclusivity").</summary>
            public required string Type { get; init; }

            /// <summary>Gets the localized label (often a token reference).</summary>
            public string? Label { get; init; }

            /// <summary>Gets the localized help text (often a token reference).</summary>
            public string? Help { get; init; }

            /// <summary>Gets the candidate rule values.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<BindingRuleValueV1> Values { get; init; }
        }

        """;

    public static string EmitRuleValue() => PocoHeader + """
        /// <summary>
        /// A single candidate value for a v1 binding rule.
        /// </summary>
        internal sealed class BindingRuleValueV1
        {
            /// <summary>Gets the underlying value selected by the rule.</summary>
            public required string Value { get; init; }

            /// <summary>Gets the localized display name (often a token reference).</summary>
            public required string Display { get; init; }

            /// <summary>Gets the names of settings to hide when this value is selected.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<string> HiddenSettings { get; init; }

            /// <summary>Gets the names of settings to show when this value is selected.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<string> ShownSettings { get; init; }
        }

        """;

    public static IEnumerable<(string HintName, string Source)> EmitStaticData(BindingsCatalogModelV1 catalog)
    {
        // Per-binding file: KnownBindings.V1.{Name}.g.cs
        foreach (BindingDefinitionModelV1 binding in catalog.Bindings)
        {
            var sb = new StringBuilder(4096);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownBindings");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class V1");
            sb.AppendLine("    {");

            string fieldName = ToFieldName(binding.Type, binding.Direction);
            sb.Append("        public static readonly BindingDefinitionV1 ").Append(fieldName).AppendLine(" =");
            EmitBinding(sb, binding, 3);
            sb.AppendLine(";");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            yield return ("KnownBindings.V1." + fieldName + ".g.cs", sb.ToString());
        }

        // Aggregate: KnownBindings.V1.g.cs
        {
            var sb = new StringBuilder(2048);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownBindings");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class V1");
            sb.AppendLine("    {");

            sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, BindingDefinitionV1> All =");
            sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, BindingDefinitionV1>");
            sb.AppendLine("            {");
            foreach (BindingDefinitionModelV1 binding in catalog.Bindings)
            {
                string fieldName = ToFieldName(binding.Type, binding.Direction);
                string key = ToCatalogKey(binding.Type, binding.Direction);
                sb.Append("                [").Append(EmitterHelpers.Literal(key)).Append("] = ").Append(fieldName).AppendLine(",");
            }

            sb.AppendLine("            };");
            sb.AppendLine();

            sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, string> Variables =");
            sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, string>");
            sb.AppendLine("            {");
            foreach (VariableEntryModelV1 variable in catalog.Variables)
            {
                sb.Append("                [").Append(EmitterHelpers.Literal(variable.Name)).Append("] = ").Append(EmitterHelpers.Literal(variable.Value)).AppendLine(",");
            }

            sb.AppendLine("            };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            yield return ("KnownBindings.V1.g.cs", sb.ToString());
        }
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(BindingsNamespace).AppendLine(";");
        sb.AppendLine();
    }

    private static string ToFieldName(string type, BindingDirectionKindV1 direction)
    {
        string sanitized = EmitterHelpers.SanitizeIdentifier(type);
        if (sanitized.Length == 0)
        {
            return sanitized;
        }

        if (char.IsLower(sanitized[0]))
        {
            sanitized = char.ToUpperInvariant(sanitized[0]) + sanitized.Substring(1);
        }

        // Trigger types already end in "Trigger" by convention; appending the direction would
        // produce awkward names like "BlobTriggerTrigger". Only suffix In/Out, where the same
        // binding type appears twice (once per direction) in bindings.json.
        return direction switch
        {
            BindingDirectionKindV1.In => sanitized + "In",
            BindingDirectionKindV1.Out => sanitized + "Out",
            BindingDirectionKindV1.Trigger => sanitized,
            _ => sanitized,
        };
    }

    // Stable, parseable lookup key: "{type}.{direction}" (e.g. "blob.in", "queueTrigger.trigger").
    private static string ToCatalogKey(string type, BindingDirectionKindV1 direction)
    {
        string dir = direction switch
        {
            BindingDirectionKindV1.In => "in",
            BindingDirectionKindV1.Out => "out",
            BindingDirectionKindV1.Trigger => "trigger",
            _ => "in",
        };

        return type + "." + dir;
    }

    private static void EmitBinding(StringBuilder sb, BindingDefinitionModelV1 binding, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);
        string inner = EmitterHelpers.Indent(depth + 1);

        sb.Append(indent).AppendLine("new BindingDefinitionV1");
        sb.Append(indent).AppendLine("{");
        AppendString(sb, inner, "Type", binding.Type);
        AppendString(sb, inner, "DisplayName", binding.DisplayName);
        sb.Append(inner).Append("Direction = BindingSchemaDirectionV1.").Append(binding.Direction switch
        {
            BindingDirectionKindV1.In => "In",
            BindingDirectionKindV1.Out => "Out",
            BindingDirectionKindV1.Trigger => "Trigger",
            _ => "In",
        }).AppendLine(",");
        AppendBool(sb, inner, "EnabledInTryMode", binding.EnabledInTryMode);
        AppendOptionalString(sb, inner, "Documentation", binding.Documentation);
        EmitSettings(sb, binding.Settings, depth + 1);
        EmitActions(sb, binding.Actions, depth + 1);
        EmitExtension(sb, binding.Extension, depth + 1);
        EmitRules(sb, binding.Rules, depth + 1);
        sb.Append(indent).Append('}');
    }

    private static void EmitSettings(StringBuilder sb, EquatableArray<BindingSettingModelV1> settings, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (settings.Length == 0)
        {
            sb.Append(indent).AppendLine("Settings = [],");
            return;
        }

        sb.Append(indent).AppendLine("Settings =");
        sb.Append(indent).AppendLine("[");
        foreach (BindingSettingModelV1 s in settings)
        {
            EmitSetting(sb, s, depth + 1);
            sb.AppendLine(",");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitSetting(StringBuilder sb, BindingSettingModelV1 setting, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);
        string inner = EmitterHelpers.Indent(depth + 1);

        sb.Append(indent).AppendLine("new BindingSettingV1");
        sb.Append(indent).AppendLine("{");
        AppendString(sb, inner, "Name", setting.Name);
        sb.Append(inner).Append("Value = BindingSettingValueTypeV1.").Append(setting.Value switch
        {
            BindingSettingValueKindV1.String => "String",
            BindingSettingValueKindV1.Bool => "Bool",
            BindingSettingValueKindV1.Int => "Int",
            BindingSettingValueKindV1.Enum => "Enum",
            BindingSettingValueKindV1.CheckBoxList => "CheckBoxList",
            _ => "String",
        }).AppendLine(",");

        if (setting.Required.HasValue)
        {
            AppendBool(sb, inner, "Required", setting.Required.Value);
        }

        AppendOptionalString(sb, inner, "Label", setting.Label);
        AppendOptionalString(sb, inner, "Help", setting.Help);

        if (setting.DefaultValue is not null)
        {
            sb.Append(inner).Append("DefaultValue = ");
            EmitDefaultValue(sb, setting.DefaultValue);
            sb.AppendLine(",");
        }

        AppendOptionalString(sb, inner, "Placeholder", setting.Placeholder);
        AppendOptionalString(sb, inner, "Resource", setting.Resource);

        EmitEnumValues(sb, setting.Enum, depth + 1);
        EmitValidators(sb, setting.Validators, depth + 1);

        sb.Append(indent).Append('}');
    }

    private static void EmitDefaultValue(StringBuilder sb, SettingDefaultValueModelV1 value)
    {
        switch (value.Kind)
        {
            case SettingDefaultValueKindV1.String:
                sb.Append(value.StringValue is null ? "null" : EmitterHelpers.Literal(value.StringValue));
                break;
            case SettingDefaultValueKindV1.Bool:
                sb.Append(value.BoolValue == true ? "true" : "false");
                break;
            case SettingDefaultValueKindV1.Long:
                sb.Append((value.LongValue ?? 0L).ToString(CultureInfo.InvariantCulture)).Append('L');
                break;
            case SettingDefaultValueKindV1.StringArray:
                sb.Append("new string[] { ");
                if (value.ArrayValue.HasValue)
                {
                    for (int i = 0; i < value.ArrayValue.Value.Length; i++)
                    {
                        if (i > 0)
                        {
                            sb.Append(", ");
                        }

                        sb.Append(EmitterHelpers.Literal(value.ArrayValue.Value[i]));
                    }
                }

                sb.Append(" }");
                break;
            default:
                sb.Append("null");
                break;
        }
    }

    private static void EmitEnumValues(StringBuilder sb, EquatableArray<BindingEnumValueModelV1> values, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (values.Length == 0)
        {
            sb.Append(indent).AppendLine("Enum = [],");
            return;
        }

        sb.Append(indent).AppendLine("Enum =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (BindingEnumValueModelV1 v in values)
        {
            sb.Append(inner).Append("new BindingEnumValueV1 { Value = ").Append(EmitterHelpers.Literal(v.Value))
                .Append(", Display = ").Append(EmitterHelpers.Literal(v.Display)).AppendLine(" },");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitValidators(StringBuilder sb, EquatableArray<BindingValidatorModelV1> validators, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (validators.Length == 0)
        {
            sb.Append(indent).AppendLine("Validators = [],");
            return;
        }

        sb.Append(indent).AppendLine("Validators =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (BindingValidatorModelV1 v in validators)
        {
            sb.Append(inner).Append("new BindingValueValidatorV1 { Expression = ").Append(EmitterHelpers.Literal(v.Expression))
                .Append(", ErrorText = ").Append(EmitterHelpers.Literal(v.ErrorText)).AppendLine(" },");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitActions(StringBuilder sb, EquatableArray<BindingActionModelV1> actions, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (actions.Length == 0)
        {
            sb.Append(indent).AppendLine("Actions = [],");
            return;
        }

        sb.Append(indent).AppendLine("Actions =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (BindingActionModelV1 a in actions)
        {
            sb.Append(inner).AppendLine("new BindingActionRefV1");
            sb.Append(inner).AppendLine("{");
            string deeper = EmitterHelpers.Indent(depth + 2);
            AppendString(sb, deeper, "Template", a.Template);
            AppendString(sb, deeper, "Binding", a.Binding);
            AppendStringArray(sb, deeper, "Settings", a.Settings);
            sb.Append(inner).AppendLine("},");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitExtension(StringBuilder sb, BindingExtensionRefModelV1? extension, int depth)
    {
        if (extension is null)
        {
            return;
        }

        string indent = EmitterHelpers.Indent(depth);
        sb.Append(indent).Append("Extension = new BindingExtensionRefV1 { Id = ").Append(EmitterHelpers.Literal(extension.Id))
            .Append(", Version = ").Append(EmitterHelpers.Literal(extension.Version)).AppendLine(" },");
    }

    private static void EmitRules(StringBuilder sb, EquatableArray<BindingRuleModelV1> rules, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (rules.Length == 0)
        {
            sb.Append(indent).AppendLine("Rules = [],");
            return;
        }

        sb.Append(indent).AppendLine("Rules =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (BindingRuleModelV1 r in rules)
        {
            sb.Append(inner).AppendLine("new BindingRuleV1");
            sb.Append(inner).AppendLine("{");
            string deeper = EmitterHelpers.Indent(depth + 2);
            AppendString(sb, deeper, "Name", r.Name);
            AppendString(sb, deeper, "Type", r.Type);
            AppendOptionalString(sb, deeper, "Label", r.Label);
            AppendOptionalString(sb, deeper, "Help", r.Help);
            EmitRuleValues(sb, r.Values, depth + 2);
            sb.Append(inner).AppendLine("},");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitRuleValues(StringBuilder sb, EquatableArray<BindingRuleValueModelV1> values, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (values.Length == 0)
        {
            sb.Append(indent).AppendLine("Values = [],");
            return;
        }

        sb.Append(indent).AppendLine("Values =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (BindingRuleValueModelV1 v in values)
        {
            sb.Append(inner).AppendLine("new BindingRuleValueV1");
            sb.Append(inner).AppendLine("{");
            string deeper = EmitterHelpers.Indent(depth + 2);
            AppendString(sb, deeper, "Value", v.Value);
            AppendString(sb, deeper, "Display", v.Display);
            AppendStringArray(sb, deeper, "HiddenSettings", v.HiddenSettings);
            AppendStringArray(sb, deeper, "ShownSettings", v.ShownSettings);
            sb.Append(inner).AppendLine("},");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void AppendString(StringBuilder sb, string indent, string name, string value)
    {
        sb.Append(indent).Append(name).Append(" = ").Append(EmitterHelpers.Literal(value)).AppendLine(",");
    }

    private static void AppendOptionalString(StringBuilder sb, string indent, string name, string? value)
    {
        if (value is not null)
        {
            AppendString(sb, indent, name, value);
        }
    }

    private static void AppendBool(StringBuilder sb, string indent, string name, bool value)
    {
        sb.Append(indent).Append(name).Append(" = ").Append(value ? "true" : "false").AppendLine(",");
    }

    private static void AppendStringArray(StringBuilder sb, string indent, string name, EquatableArray<string> values)
    {
        sb.Append(indent).Append(name).Append(" = [");
        for (int i = 0; i < values.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(EmitterHelpers.Literal(values[i]));
        }

        sb.AppendLine("],");
    }
}
