parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false
- name: skipBranchValidation
  displayName: Allow non-release source
  type: boolean
  default: false

# Release has no triggers outside of pipeline
trigger: none
pr: none

extends:
  template: /eng/ci/templates/pipelines/release-packages.yml@self
  parameters:
    public: ${{ parameters.public }}
    skipBranchValidation: ${{ parameters.skipBranchValidation }}
    folder: workloads/dotnet
    projects: |
      $(Build.SourcesDirectory)/src/Workloads/Stacks/DotNet/Workloads.DotNet.csproj
      $(Build.SourcesDirectory)/test/Workloads/Stacks/DotNet.Tests/Workloads.DotNet.Tests.csproj
