parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false

# Release has no triggers outside of pipeline
trigger: none
pr: none

extends:
  template: /eng/ci/templates/pipelines/release-packages.yml@self
  parameters:
    public: ${{ parameters.public }}
    folder: workloads/powershell-worker
    projects: |
      $(Build.SourcesDirectory)/src/Workloads/Workers/PowerShell/Workloads.Workers.PowerShell.csproj
