parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false

# Release has no triggers outside of pipeline
trigger: none
pr: none

extends:
  template: /eng/ci/templates/pipelines/release-packages.yml@self
  parameters:
    public: ${{ parameters.public }}
    folder: workloads/templates/node
    projects: |
      $(Build.SourcesDirectory)/src/Workloads/Templates/Node/Workloads.Templates.Node.csproj
    tagSpec:
      tagPrefix: templates-node
      allowChannels: true
    build_args: -p:TemplatesVersion=$(ReleaseTagVersion) -p:TemplatesChannel=$(ReleaseTagChannel) -p:VersionSuffix=$(ReleaseTagSuffix)
