parameters:
- name: public
  displayName: Publish to nuget.org?
  type: boolean
  default: false

# Release has no triggers outside of pipeline
trigger: none
pr: none

extends:
  template: /eng/ci/templates/pipelines/release-packages.yml@self
  parameters:
    public: ${{ parameters.public }}
    folder: workloads/node
    projects: |
      $(Build.SourcesDirectory)/src/Workloads/Stacks/Node/Workloads.Node.csproj
      $(Build.SourcesDirectory)/test/Workloads/Stacks/Node.Tests/Workloads.Node.Tests.csproj
