parameters:
  - name: arch
    type: string
  - name: displayName
    type: string
  - name: isNightlyBuild
    type: boolean

jobs:
- job: AssembleArtifact${{ parameters.displayName }}
  displayName: "Assemble ${{ parameters.arch }}"
  templateContext:
    ${{ if eq(parameters.isNightlyBuild, false) }}:
      inputs:
        - input: pipelineArtifact
          pipeline: core-tools-host
          artifactName: coretools-host-linux-signed
          targetPath: $(Pipeline.Workspace)/core-tools-host/coretools-host-linux-signed
        - input: pipelineArtifact
          pipeline: core-tools-host
          artifactName: coretools-host-windows
          targetPath: $(Pipeline.Workspace)/core-tools-host/coretools-host-windows
        - input: pipelineArtifact
          pipeline: core-tools-inproc
          artifactName: coretools-cli-inproc6
          targetPath: $(Pipeline.Workspace)/core-tools-inproc/coretools-cli-inproc6
        - input: pipelineArtifact
          pipeline: core-tools-inproc
          artifactName: coretools-cli-inproc8
          targetPath: $(Pipeline.Workspace)/core-tools-inproc/coretools-cli-inproc8
        - input: pipelineArtifact
          pipeline: core-tools-default
          artifactName: coretools-cli
          targetPath: $(Pipeline.Workspace)/core-tools-default/coretools-cli

    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
      - output: pipelineArtifact
        displayName: Publish assembled artifact ${{ parameters.arch }}
        targetPath: $(Build.ArtifactStagingDirectory)/core-tools
        artifact: coretools-cli-${{ parameters.arch }}
      - output: pipelineArtifact
        displayName: Publish metadata.json
        targetPath: $(Build.ArtifactStagingDirectory)/metadata.json
        artifact: coretools-cli-metadata-json
        condition: and(succeeded(), eq('${{ parameters.arch }}', 'min.win-x64'))

  steps:
  - checkout: self

  # Conditional download of artifacts based on isNightlyBuild parameter
  - ${{ if eq(parameters.isNightlyBuild, true) }}:
    # Download from ADO feed for nightly builds
    - task: UniversalPackages@0
      displayName: 'Download core-tools-host (Linux signed) from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-host-linux-signed'
        vstsPackageVersion: '4.0.*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-host/coretools-host-linux-signed'

    - task: UniversalPackages@0
      displayName: 'Download core-tools-host (Windows) from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-host-windows'
        vstsPackageVersion: '4.0.*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-host/coretools-host-windows'

    - task: UniversalPackages@0
      displayName: 'Download core-tools-inproc6 from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-cli-inproc6'
        vstsPackageVersion: '4.0.*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-inproc/coretools-cli-inproc6'

    - task: UniversalPackages@0
      displayName: 'Download core-tools-inproc8 from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-cli-inproc8'
        vstsPackageVersion: '4.0.*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-inproc/coretools-cli-inproc8'

    - task: UniversalPackages@0
      displayName: 'Download core-tools-default from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-cli'
        vstsPackageVersion: '4.0.*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-default/coretools-cli'

  - task: DotNetCoreCLI@2
    displayName: "Run ArtifactAssembler"
    inputs:
      command: run
      projects: "$(Build.SourcesDirectory)/src/Cli/ArtifactAssembler/Azure.Functions.Cli.ArtifactAssembler.csproj"
      arguments: '-c release -- "Azure.Functions.Cli.${{ parameters.arch }}"'
      workingDirectory: '$(Pipeline.Workspace)'

  - ${{ if eq(parameters.arch, 'min.win-x64') }}:
    - task: PowerShell@2
      displayName: 'Generate metadata.json file'
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/generateMetadataFile.ps1'
        arguments: '-StagingDirectory "$(Pipeline.Workspace)/staging"'
        workingDirectory: '$(Pipeline.Workspace)'

  - ${{ if startsWith(parameters.arch, 'win') }}:
    - task: PowerShell@2
      displayName: 'Generate MSI files'
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/generateMsiFiles.ps1'
        arguments: '-ArtifactsPath "$(Pipeline.Workspace)\staging\coretools-cli"'
        workingDirectory: '$(Build.SourcesDirectory)/build'

  - ${{ if startsWith(parameters.arch, 'win-x') }}:
    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign MSI files
        folderPath: $(Pipeline.Workspace)/staging/coretools-cli
        pattern: '*.msi'
        signType: 'inline'
        inlineOperation: |
          [
            {
              "KeyCode": "CP-230012",
              "OperationCode": "SigntoolSign",
              "Parameters": {
                "OpusName": "Microsoft",
                "OpusInfo": "http://www.microsoft.com",
                "FileDigest": "/fd \"SHA256\"",
                "PageHash": "/NPH",
                "TimeStamp": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
              },
              "ToolName": "sign",
              "ToolVersion": "1.0"
            },
            {
              "KeyCode": "CP-230012",
              "OperationCode": "SigntoolVerify",
              "Parameters": {},
              "ToolName": "sign",
              "ToolVersion": "1.0"
            }
          ]

  - ${{ if eq(parameters.arch, 'min.win-x64') }}:
    - task: PowerShell@2
      displayName: 'Test Artifacts - Visual Studio'
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/testVsArtifacts.ps1'
        arguments: '-StagingDirectory "$(Pipeline.Workspace)/staging/coretools-visualstudio"'

  - ${{ if startsWith(parameters.arch, 'win') }}:
    - task: PowerShell@2
      displayName: 'Test Artifacts'
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/testArtifacts.ps1'
        arguments: '-StagingDirectory "$(Pipeline.Workspace)/staging/coretools-cli"'

  - task: DotNetCoreCLI@2
    displayName: 'Zip Artifacts'
    inputs:
      command: run
      projects: '$(Build.SourcesDirectory)/src/Cli/ArtifactAssembler/Azure.Functions.Cli.ArtifactAssembler.csproj'
      arguments: '--no-build -c release -- zip'
      workingDirectory: '$(Pipeline.Workspace)'

  - task: PowerShell@2
    displayName: 'Generate SHA files'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/generateSha.ps1'
      arguments: '-CurrentDirectory "$(Pipeline.Workspace)"'

  - task: CopyFiles@2
    displayName: 'Copy Files to Artifact Staging Directory'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/staging'
      Contents: 'coretools-*/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/core-tools'

  - ${{ if eq(parameters.arch, 'min.win-x64') }}:
    - task: CopyFiles@2
      displayName: 'Copy metadata.json to Artifact Staging Directory'
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/staging'
        Contents: 'metadata.json'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'