parameters:
  - name: isNightlyBuild
    type: boolean
    default: false

jobs:
- job: DownloadNuGetPackage
  displayName: "Download NuGet Package"
  templateContext:
    ${{ if eq(parameters.isNightlyBuild, false) }}:
      inputs:
        - input: pipelineArtifact
          pipeline: core-tools-default
          artifactName: func-cli
          targetPath: $(Pipeline.Workspace)/func-cli-default/func-cli
    outputs:
      - output: pipelineArtifact
        displayName: Publish nuget package
        targetPath: $(Pipeline.Workspace)/nugetPackage
        artifact: func-nuget-package
  steps:
  - checkout: self

  # Conditional download of artifacts based on isNightlyBuild parameter
  - ${{ if eq(parameters.isNightlyBuild, true) }}:
    - template: /eng/ci/templates/official/steps/download-latest-from-feed.yml@self
      parameters:
        defaultCliOnly: true

  - task: CopyFiles@2
    displayName: 'Copy NuGet package to output directory'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/func-cli-default/func-cli'
      Contents: 'Microsoft.Azure.Functions.CoreTools.*.nupkg'
      TargetFolder: '$(Pipeline.Workspace)/nugetPackage'
      OverWrite: true