parameters:
  - name: isNightlyBuild
    type: boolean
    default: false

jobs:
- job: DownloadNuGetPackage
  displayName: "Download NuGet Package"
  templateContext:
    ${{ if eq(parameters.isNightlyBuild, false) }}:
      inputs:
        - input: pipelineArtifact
          pipeline: core-tools-default
          artifactName: func-cli
          targetPath: $(Pipeline.Workspace)/core-tools-default/func-cli
    outputs:
      - output: pipelineArtifact
        displayName: Publish nuget package
        targetPath: $(Pipeline.Workspace)/nugetPackage
        artifact: func-nuget-package
  steps:
  - checkout: self

  # Conditional download of artifacts based on isNightlyBuild parameter
  - ${{ if eq(parameters.isNightlyBuild, true) }}:
    # Download from ADO feed for nightly builds
    - task: DownloadPackage@1
      displayName: 'Download core-tools-default from feed'
      inputs:
        packageType: 'upack'
        feed: 'internal/core-tools-nightly-build'
        definition: 'func-cli'
        version: '*'
        downloadPath: '$(Pipeline.Workspace)/core-tools-default/func-cli'

  - task: CopyFiles@2
    displayName: 'Copy NuGet package to output directory'
    inputs:
      SourceFolder: '$(Pipeline.Workspace)/core-tools-default/func-cli'
      Contents: 'Microsoft.Azure.Functions.CoreTools.*.nupkg'
      TargetFolder: '$(Pipeline.Workspace)/nugetPackage'
      OverWrite: true