jobs:
  - job: LinuxPackage
  condition: ne(variables['LinuxPackageBuildTag'], '')
  timeoutInMinutes: "120"
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  # Bash v3
  # Run a Bash script on macOS, Linux, or Windows.
  - task: Bash@3
    inputs:
      targetType: 'inline'  # Specify 'filePath' if you want to use an external script file.
      script: |
        cd publish-scripts
        python3 -m venv publish-env
        source publish-env/bin/activate
        pip install -r requirements.txt
        apt-get install fakeroot
        major_version=$(echo "$linuxBuildNumber" | cut -d'.' -f1)
        python driver.py "$linuxBuildNumber" "$major_version"
        python driver.py "$linuxBuildNumber"
        export DEB_PACKAGE="$(readlink -f artifact/*$RELEASE_VERSION*)"
        echo "${DEB_PACKAGE}"
      bashEnvValue: '~/.profile'  # Set value for BASH_ENV environment variable
    env:
      linuxBuildNumber: $(LinuxPackageBuildTag)      
  - pwsh: |
      echo $env:LinuxPackageAccountName
      $majorVersion = [math]::Floor([double]$env:LinuxPackageBuildTag.Split(".")[0])
      az storage blob upload -f /home/vsts/work/1/s/publish-scripts/artifact/azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb -c unsigned -n azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
      az storage blob upload -f /home/vsts/work/1/s/publish-scripts/artifact/azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb -c unsigned -n azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
    env:
      LinuxPackageAccountName: $(LinuxPackageAccountName)
      LinuxPackageAccountKey: $(LinuxPackageAccountKey)
      LinuxPackageBuildTag: $(LinuxPackageBuildTag)
    displayName: 'Upload Core Tools Unsigned Linux Package to the storage'
  - task: EsrpCodeSigning@3
    displayName: Sign
    inputs:
      ConnectedServiceName: $(ESRPServiceConnectionName)
      FolderPath: '/home/vsts/work/1/s/publish-scripts/artifact/'
      Pattern: '*.deb'
      signConfigType: 'inlineSignParams'
      inlineOperation: |
        [
          {
            "keyCode": "CP-450779-Pgp",
            "operationSetCode": "LinuxSign",
            "parameters": [],
            "toolName": "signtool.exe",
            "toolVersion": "1.0"
          }
        ]
      SessionTimeout: '60'
      MaxConcurrency: '50'
      MaxRetryAttempts: '5'
  - pwsh: |
      echo $env:LinuxPackageAccountName
      $majorVersion = [math]::Floor([double]$env:LinuxPackageBuildTag.Split(".")[0])
      az storage blob upload -f /home/vsts/work/1/s/publish-scripts/artifact/azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb -c signed -n azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
      az storage blob upload -f /home/vsts/work/1/s/publish-scripts/artifact/azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb -c signed -n azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
    env:
      LinuxPackageAccountName: $(LinuxPackageAccountName)
      LinuxPackageAccountKey: $(LinuxPackageAccountKey)
      LinuxPackageBuildTag: $(LinuxPackageBuildTag)
    displayName: 'Upload Core Tools Signed Linux Package to the storage'
