jobs:
- job: LinuxPackage
  condition: and(ne(variables['LinuxPackageBuildTag'], ''), ne(variables['ConsolidatedBuildId'], ''))
  timeoutInMinutes: "120"

  pool:
    name: 1es-pool-azfunc
    image: 1es-ubuntu-22.04
    os: linux

  variables:
    drop_path: $(Build.ArtifactStagingDirectory)
    pkg_drop_path: $(drop_path)/drop_debian

  templateContext:
    outputParentDirectory: $(drop_path)
    outputs:
    - output: pipelineArtifact
      displayName: Publish debian package
      path: $(pkg_drop_path)
      artifact: drop_debian

  steps:
  - task: Bash@3
    displayName: 'Build DEB package'
    inputs:
      targetType: 'inline'
      script: |
        cd publish-scripts
        python3 -m venv publish-env
        source publish-env/bin/activate

        pip install -r requirements.txt
        pip install wget

        sudo apt-get install fakeroot
        major_version=$(echo "$linuxBuildNumber" | cut -d'.' -f1)
        python driver.py "$linuxBuildNumber" "$consolidatedBuildId" "$major_version"
        python driver.py "$linuxBuildNumber" "$consolidatedBuildId"
        export DEB_PACKAGE="$(readlink -f artifact/*$RELEASE_VERSION*)"
        echo "${DEB_PACKAGE}"
      bashEnvValue: '~/.profile'  # Set value for BASH_ENV environment variable
    env:
      linuxBuildNumber: $(LinuxPackageBuildTag)
      consolidatedBuildId: $(ConsolidatedBuildId)

  - template: ci/sign-files.yml@eng
    parameters:
      displayName: 'Sign'
      folderPath: '/mnt/vss/_work/1/s/publish-scripts/artifact'
      pattern: '*.deb'
      signType: inline
      inlineOperation: |
        [
          {
            "keyCode": "CP-450779-Pgp",
            "operationSetCode": "LinuxSign",
            "parameters": [],
            "toolName": "signtool.exe",
            "toolVersion": "1.0"
          }
        ]

  - pwsh: |
      echo $env:LinuxPackageAccountName
      $majorVersion = [math]::Floor([double]$env:LinuxPackageBuildTag.Split(".")[0])
      az storage blob upload -f /mnt/vss/_work/1/s/publish-scripts/artifact/azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb -c signed -n azure-functions-core-tools_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
      az storage blob upload -f /mnt/vss/_work/1/s/publish-scripts/artifact/azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb -c signed -n azure-functions-core-tools-$($majorVersion)_$env:LinuxPackageBuildTag-1.deb --account-name $env:LinuxPackageAccountName --account-key $env:LinuxPackageAccountKey
    env:
      LinuxPackageAccountName: $(LinuxPackageAccountName)
      LinuxPackageAccountKey: $(LinuxPackageAccountKey)
      LinuxPackageBuildTag: $(LinuxPackageBuildTag)
    displayName: 'Upload Core Tools Signed Linux Package to the storage'
    condition: eq(variables['UploadSignedPackages'], 'true') # This is a UI variable that defaults to false

  - task: Bash@3
    displayName: 'Copy DEB package to drop'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p $drop
        cp -r /mnt/vss/_work/1/s/publish-scripts/artifact/* $drop
    env:
      drop: $(pkg_drop_path)
