jobs:
- job: MergeArtifacts
  displayName: 'Merge artifacts'

  templateContext:
    type: artifactJob

    inputs:
    - input: pipelineArtifact
      artifactName: func-cli-linux-x64
      targetPath: $(Pipeline.Workspace)/func-cli

    - input: pipelineArtifact
      artifactName: func-cli-osx-x64
      targetPath: $(Pipeline.Workspace)/func-cli
    - input: pipelineArtifact
      artifactName: func-cli-osx-arm64
      targetPath: $(Pipeline.Workspace/func-cli

    - input: pipelineArtifact
      artifactName: func-cli-win-x86
      targetPath: $(Pipeline.Workspace)/func-cli
    - input: pipelineArtifact
      artifactName: func-cli-win-x64
      targetPath: $(Pipeline.Workspace)/func-cli
    - input: pipelineArtifact
      artifactName: func-cli-win-arm64
      targetPath: $(Pipeline.Workspace)/func-cli

    - input: pipelineArtifact
      artifactName: func-cli-min.win-x86
      targetPath: $(Pipeline.Workspace)/func-cli
    - input: pipelineArtifact
      artifactName: func-cli-min.win-x64
      targetPath: $(Pipeline.Workspace)/func-cli
    - input: pipelineArtifact
      artifactName: func-cli-min.win-arm64
      targetPath: $(Pipeline.Workspace)/func-cli

    - input: pipelineArtifact
      artifactName: func-cli-nupkg
      targetPath: $(Pipeline.Workspace)/func-cli

    outputs:
    - output: pipelineArtifact
      targetPath: $(Pipeline.Workspace)/func-cli
      artifactName: 'func-cli'