parameters:
  - name: isNightlyBuild
    type: boolean
    default: false

jobs:
- job: ProcessNuGetPackage
  displayName: "Process NuGet Package"
  templateContext:
    ${{ if eq(parameters.isNightlyBuild, false) }}:
      inputs:
        - input: pipelineArtifact
          pipeline: core-tools-default
          artifactName: coretools-cli
          targetPath: $(Pipeline.Workspace)/core-tools-default/coretools-cli
    outputs:
      - output: pipelineArtifact
        displayName: Publish nuget package
        targetPath: $(Pipeline.Workspace)/nugetPackage
        artifact: coretools-nuget-package
  steps:
  - checkout: self

  # Conditional download of artifacts based on isNightlyBuild parameter
  - ${{ if eq(parameters.isNightlyBuild, true) }}:
    # Download from ADO feed for nightly builds
    - task: UniversalPackages@0
      displayName: 'Download core-tools-default from feed'
      inputs:
        command: download
        vstsFeed: 'internal/core-tools-nightly-build'
        vstsFeedPackage: 'coretools-cli'
        vstsPackageVersion: '4.0.*+*'
        downloadDirectory: '$(Pipeline.Workspace)/core-tools-default/coretools-cli'

  - task: PowerShell@2
    displayName: 'Process and move nuget package to staging directory'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/moveNugetPackage.ps1'
      arguments: '-CurrentDirectory "$(Pipeline.Workspace)"'