parameters:
  - name: jobDisplayName
    type: string
    default: 'Process NuGet Package'
  - name: isNightlyBuild
    type: boolean
    default: false

jobs:
- job: ProcessNuGetPackage
  displayName: "${{ parameters.jobDisplayName }}"
  templateContext:
    inputs:
      # Dynamically select the appropriate pipeline for default artifacts based on whether it's a nightly build
      - ${{ if parameters.isNightlyBuild }}:
        - input: pipelineArtifact
          pipeline: core-tools-default-nightly
          artifactName: drop
          targetPath: $(Pipeline.Workspace)/core-tools-default/drop
      - ${{ else }}:
        - input: pipelineArtifact
          pipeline: core-tools-default
          artifactName: drop
          targetPath: $(Pipeline.Workspace)/core-tools-default/drop
    outputs:
      - output: pipelineArtifact
        displayName: Publish nuget package
        targetPath: $(Pipeline.Workspace)/nugetPackage
        artifact: drop-nuget-package
  steps:
  - checkout: self

  - task: PowerShell@2
    displayName: 'Process and move nuget package to staging directory'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/eng/scripts/ArtifactAssemblerHelpers/moveNugetPackage.ps1'
      arguments: '-CurrentDirectory "$(Pipeline.Workspace)"'