parameters:
  - name: artifactName
    type: string
  - name: packageName
    type: string

jobs:
- job: UploadArtifactToFeed
  displayName: 'Upload artifact to Feed'
  timeoutInMinutes: "180"

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download artifact
    inputs:
      artifact: '${{ parameters.artifactName }}'
      path: $(Build.ArtifactStagingDirectory)/drop

  - task: PowerShell@2
    displayName: 'Extract version number'
    inputs:
      targetType: 'inline'
      script: |
        # For in-proc, we need to remove the 'inproc_' prefix from the build number
        $buildNumberVersion = "$(Build.BuildNumber)"
        $version = $buildNumberVersion -replace '^[^_]*_',''
        Write-Host "Stripped version: $version"
        Write-Host "##vso[task.setvariable variable=FuncVersionNumber]$version"

  - bash: echo $(FuncVersionNumber)
    displayName: 'Print version number'

  - task: UniversalPackages@0
    displayName: Publish to feed
    inputs:
      command: publish
      publishDirectory: '$(Build.ArtifactStagingDirectory)/drop'
      vstsFeedPublish: 'internal/core-tools-nightly-build'
      vstsFeedPackagePublish: '${{ parameters.packageName }}'
      versionOption: custom
      versionPublish: '$(FuncVersionNumber)'
      packagePublishDescription: 'Core tools default nightly build'