// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Collections.Generic;
using System.Text;

using Azure.Functions.Cli.Tools.TemplateGenerator.Model;

using Microsoft.CodeAnalysis.CSharp;

namespace Azure.Functions.Cli.Tools.TemplateGenerator;

internal static class TemplateEmitter
{
    private const string Header = """
        // <auto-generated/>
        #nullable enable

        namespace Azure.Functions.Cli.Templates;

        """;

    public static string EmitFunctionTemplate() => Header + """
        /// <summary>
        /// Represents an Azure Functions template definition.
        /// </summary>
        internal sealed class FunctionTemplate
        {
            /// <summary>Gets the unique template identifier.</summary>
            public required string Id { get; init; }

            /// <summary>Gets the template name (derived from Id, without the language suffix).</summary>
            public required string Name { get; init; }

            /// <summary>Gets the runtime version.</summary>
            public required string Runtime { get; init; }

            /// <summary>Gets the template files (filename to content).</summary>
            public required global::System.Collections.Generic.IReadOnlyDictionary<string, string> Files { get; init; }

            /// <summary>Gets the function definition.</summary>
            public required FunctionDefinition Function { get; init; }

            /// <summary>Gets the template metadata.</summary>
            public required TemplateMetadata Metadata { get; init; }
        }

        """;

    public static string EmitFunctionDefinition() => Header + """
        /// <summary>
        /// Represents the function configuration within a template.
        /// </summary>
        internal sealed class FunctionDefinition
        {
            /// <summary>Gets the function bindings.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<TemplateBinding> Bindings { get; init; }

            /// <summary>Gets the script file path, if any.</summary>
            public string? ScriptFile { get; init; }

            /// <summary>Gets whether the function is disabled.</summary>
            public bool? Disabled { get; init; }

            /// <summary>Gets the entry point, if any.</summary>
            public string? EntryPoint { get; init; }
        }

        """;

    public static string EmitBindingDirection() => Header + """
        /// <summary>
        /// Represents the direction of a function binding.
        /// </summary>
        internal enum BindingDirection
        {
            /// <summary>Input binding.</summary>
            In,

            /// <summary>Output binding.</summary>
            Out,
        }

        """;

    public static string EmitTemplateBinding() => Header + """
        /// <summary>
        /// Represents a binding in a function template.
        /// </summary>
        internal sealed class TemplateBinding
        {
            /// <summary>Gets the binding name.</summary>
            public required string Name { get; init; }

            /// <summary>Gets the binding type.</summary>
            public required string Type { get; init; }

            /// <summary>Gets the binding direction.</summary>
            public required BindingDirection Direction { get; init; }

            /// <summary>Gets any additional binding properties as extension data.</summary>
            [global::System.Text.Json.Serialization.JsonExtensionData]
            public global::System.Collections.Generic.IDictionary<string, object?>? ExtensionData { get; set; }
        }

        """;

    public static string EmitTemplateMetadata() => Header + """
        /// <summary>
        /// Represents metadata about a function template.
        /// </summary>
        internal sealed class TemplateMetadata
        {
            /// <summary>Gets the default function name.</summary>
            public required string DefaultFunctionName { get; init; }

            /// <summary>Gets the description.</summary>
            public required string Description { get; init; }

            /// <summary>Gets the display name.</summary>
            public required string Name { get; init; }

            /// <summary>Gets the programming language.</summary>
            public required string Language { get; init; }

            /// <summary>Gets the template categories.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<string> Category { get; init; }

            /// <summary>Gets the category style.</summary>
            public required string CategoryStyle { get; init; }

            /// <summary>Gets whether the template is enabled in try mode.</summary>
            public required bool EnabledInTryMode { get; init; }

            /// <summary>Gets the user prompt fields.</summary>
            public global::System.Collections.Generic.IReadOnlyList<string>? UserPrompt { get; init; }

            /// <summary>Gets the template filters.</summary>
            public global::System.Collections.Generic.IReadOnlyList<string>? Filters { get; init; }

            /// <summary>Gets the trigger type name.</summary>
            public string? Trigger { get; init; }
        }

        """;

    public static IEnumerable<(string HintName, string Source)> EmitStaticData(EquatableArray<TemplateModel> templates)
    {
        // Emit each template as its own partial class file with a static readonly field.
        foreach (TemplateModel template in templates)
        {
            var sb = new StringBuilder(4096);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownTemplates");
            sb.AppendLine("{");

            string fieldName = SanitizeIdentifier(template.Name);
            sb.Append("    public static readonly FunctionTemplate ").Append(fieldName).AppendLine(" =");
            EmitTemplate(sb, template, 2);
            sb.AppendLine(";");

            sb.AppendLine("}");
            yield return ("KnownTemplates." + fieldName + ".g.cs", sb.ToString());
        }

        // Emit the All dictionary that references each static field.
        {
            var sb = new StringBuilder(1024);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownTemplates");
            sb.AppendLine("{");
            sb.AppendLine("    public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, FunctionTemplate> All =");
            sb.AppendLine("        new global::System.Collections.Generic.Dictionary<string, FunctionTemplate>") ;
            sb.AppendLine("        {");

            foreach (TemplateModel template in templates)
            {
                string fieldName = SanitizeIdentifier(template.Name);
                sb.Append("            [").Append(Literal(template.Name)).Append("] = ").Append(fieldName).AppendLine(",");
            }

            sb.AppendLine("        };");
            sb.AppendLine("}");
            yield return ("KnownTemplates.g.cs", sb.ToString());
        }
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Azure.Functions.Cli.Templates;");
        sb.AppendLine();
    }

    private static string SanitizeIdentifier(string name)
    {
        char[] chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (!char.IsLetterOrDigit(chars[i]) && chars[i] != '_')
            {
                chars[i] = '_';
            }
        }

        return new string(chars);
    }

    private static void EmitTemplate(StringBuilder sb, TemplateModel template, int depth)
    {
        string indent = Indent(depth);
        string inner = Indent(depth + 1);

        sb.Append(indent).AppendLine("new FunctionTemplate");
        sb.Append(indent).AppendLine("{");
        AppendString(sb, inner, "Id", template.Id);
        AppendString(sb, inner, "Name", template.Name);
        AppendString(sb, inner, "Runtime", template.Runtime);
        EmitFiles(sb, template.Files, depth + 1);
        EmitFunction(sb, template.Function, depth + 1);
        EmitMetadata(sb, template.Metadata, depth + 1);
        sb.Append(indent).Append('}');
    }

    private static void EmitFiles(StringBuilder sb, EquatableArray<FileModel> files, int depth)
    {
        string indent = Indent(depth);
        string inner = Indent(depth + 1);

        if (files.Length == 0)
        {
            sb.Append(indent).AppendLine("Files = new global::System.Collections.Generic.Dictionary<string, string>(),");
            return;
        }

        sb.Append(indent).AppendLine("Files = new global::System.Collections.Generic.Dictionary<string, string>");
        sb.Append(indent).AppendLine("{");
        foreach (FileModel file in files)
        {
            sb.Append(inner).Append('[').Append(Literal(file.Name)).Append("] = ").Append(Literal(file.Content)).AppendLine(",");
        }

        sb.Append(indent).AppendLine("},");
    }

    private static void EmitFunction(StringBuilder sb, FunctionModel function, int depth)
    {
        string indent = Indent(depth);
        string inner = Indent(depth + 1);
        string bindingIndent = Indent(depth + 2);

        sb.Append(indent).AppendLine("Function = new FunctionDefinition");
        sb.Append(indent).AppendLine("{");

        // Bindings
        if (function.Bindings.Length == 0)
        {
            sb.Append(inner).AppendLine("Bindings = [],");
        }
        else
        {
            sb.Append(inner).AppendLine("Bindings =");
            sb.Append(inner).AppendLine("[");
            foreach (BindingModel binding in function.Bindings)
            {
                EmitBinding(sb, binding, depth + 2);
                sb.AppendLine(",");
            }

            sb.Append(inner).AppendLine("],");
        }

        AppendOptionalString(sb, inner, "ScriptFile", function.ScriptFile);
        AppendOptionalBool(sb, inner, "Disabled", function.Disabled);
        AppendOptionalString(sb, inner, "EntryPoint", function.EntryPoint);

        sb.Append(indent).AppendLine("},");
    }

    private static void EmitBinding(StringBuilder sb, BindingModel binding, int depth)
    {
        string indent = Indent(depth);
        string inner = Indent(depth + 1);

        sb.Append(indent).AppendLine("new TemplateBinding");
        sb.Append(indent).AppendLine("{");

        AppendString(sb, inner, "Name", binding.Name);
        AppendString(sb, inner, "Type", binding.Type);
        sb.Append(inner).Append("Direction = BindingDirection.").Append(binding.Direction == BindingDirectionKind.In ? "In" : "Out").AppendLine(",");

        if (binding.ExtensionData.Length > 0)
        {
            sb.Append(inner).AppendLine("ExtensionData = new global::System.Collections.Generic.Dictionary<string, object?>");
            sb.Append(inner).AppendLine("{");
            string dictInner = Indent(depth + 2);
            foreach (BindingExtensionEntry entry in binding.ExtensionData)
            {
                sb.Append(dictInner).Append('[').Append(Literal(entry.Key)).Append("] = ");
                EmitExtensionValue(sb, entry.Value);
                sb.AppendLine(",");
            }

            sb.Append(inner).AppendLine("},");
        }

        sb.Append(indent).Append('}');
    }

    private static void EmitExtensionValue(StringBuilder sb, BindingExtensionValue value)
    {
        switch (value.Kind)
        {
            case BindingExtensionValueKind.String:
                sb.Append(value.StringValue is null ? "null" : Literal(value.StringValue));
                break;
            case BindingExtensionValueKind.Bool:
                sb.Append(value.BoolValue == true ? "true" : "false");
                break;
            case BindingExtensionValueKind.StringArray:
                sb.Append("new string[] { ");
                if (value.ArrayValue.HasValue)
                {
                    for (int i = 0; i < value.ArrayValue.Value.Length; i++)
                    {
                        if (i > 0)
                        {
                            sb.Append(", ");
                        }

                        sb.Append(Literal(value.ArrayValue.Value[i]));
                    }
                }

                sb.Append(" }");
                break;
        }
    }

    private static void EmitMetadata(StringBuilder sb, MetadataModel metadata, int depth)
    {
        string indent = Indent(depth);
        string inner = Indent(depth + 1);

        sb.Append(indent).AppendLine("Metadata = new TemplateMetadata");
        sb.Append(indent).AppendLine("{");

        AppendString(sb, inner, "DefaultFunctionName", metadata.DefaultFunctionName);
        AppendString(sb, inner, "Description", metadata.Description);
        AppendString(sb, inner, "Name", metadata.Name);
        AppendString(sb, inner, "Language", metadata.Language);
        AppendStringArray(sb, inner, "Category", metadata.Category);
        AppendString(sb, inner, "CategoryStyle", metadata.CategoryStyle);
        AppendBool(sb, inner, "EnabledInTryMode", metadata.EnabledInTryMode);
        AppendOptionalStringArray(sb, inner, "UserPrompt", metadata.UserPrompt);
        AppendOptionalStringArray(sb, inner, "Filters", metadata.Filters);
        AppendOptionalString(sb, inner, "Trigger", metadata.Trigger);

        sb.Append(indent).AppendLine("},");
    }

    private static void AppendString(StringBuilder sb, string indent, string name, string value)
    {
        sb.Append(indent).Append(name).Append(" = ").Append(Literal(value)).AppendLine(",");
    }

    private static void AppendOptionalString(StringBuilder sb, string indent, string name, string? value)
    {
        if (value is not null)
        {
            AppendString(sb, indent, name, value);
        }
    }

    private static void AppendBool(StringBuilder sb, string indent, string name, bool value)
    {
        sb.Append(indent).Append(name).Append(" = ").Append(value ? "true" : "false").AppendLine(",");
    }

    private static void AppendOptionalBool(StringBuilder sb, string indent, string name, bool? value)
    {
        if (value.HasValue)
        {
            AppendBool(sb, indent, name, value.Value);
        }
    }

    private static void AppendStringArray(StringBuilder sb, string indent, string name, EquatableArray<string> values)
    {
        sb.Append(indent).Append(name).Append(" = [");
        for (int i = 0; i < values.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(Literal(values[i]));
        }

        sb.AppendLine("],");
    }

    private static void AppendOptionalStringArray(StringBuilder sb, string indent, string name, EquatableArray<string>? values)
    {
        if (values.HasValue)
        {
            AppendStringArray(sb, indent, name, values.Value);
        }
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static string Indent(int depth) => new(' ', depth * 4);
}
