// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Azure.Functions.Cli.Tools.TemplateGenerator.Common;

internal static class EmitterHelpers
{
    public const string TemplatesNamespace = "Azure.Functions.Cli.Templates";

    public const string PocoHeader = """
        // <auto-generated/>
        #nullable enable

        namespace Azure.Functions.Cli.Templates;

        """;

    public static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(TemplatesNamespace).AppendLine(";");
        sb.AppendLine();
    }

    public static string SanitizeIdentifier(string name)
    {
        char[] chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (!char.IsLetterOrDigit(chars[i]) && chars[i] != '_')
            {
                chars[i] = '_';
            }
        }

        return new string(chars);
    }

    public static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    public static string Indent(int depth) => new(' ', depth * 4);
}
