// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace Azure.Functions.Cli.Tools.TemplateGenerator.Common;

internal static class EmitterHelpers
{
    public const string TemplatesNamespace = "Azure.Functions.Cli.Templates";

    public const string PocoHeader = """
        // <auto-generated/>
        #nullable enable

        namespace Azure.Functions.Cli.Templates;

        """;

    public static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(TemplatesNamespace).AppendLine(";");
        sb.AppendLine();
    }

    public static string SanitizeIdentifier(string name)
    {
        char[] chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            if (!char.IsLetterOrDigit(chars[i]) && chars[i] != '_')
            {
                chars[i] = '_';
            }
        }

        return new string(chars);
    }

    /// <summary>
    /// Converts a kebab/camel-cased id (e.g. "httpTrigger-route") into a PascalCase identifier
    /// (e.g. "HttpTriggerRoute"). Each '-' separated segment is concatenated with its first
    /// character upper-cased; remaining characters are preserved.
    /// </summary>
    public static string KebabToPascal(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        string[] parts = value.Split('-');
        var sb = new StringBuilder(value.Length);
        foreach (string part in parts)
        {
            if (part.Length == 0)
            {
                continue;
            }

            string sanitized = SanitizeIdentifier(part);
            if (sanitized.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(sanitized[0]));
            if (sanitized.Length > 1)
            {
                sb.Append(sanitized, 1, sanitized.Length - 1);
            }
        }

        return sb.ToString();
    }

    public static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    public static string Indent(int depth) => new(' ', depth * 4);
}
