trigger:
  branches:
    include:
    - main
    - vnext
    - feature/*
  paths:
    include:
    - src/Func.Cli.Abstractions/**
    - eng/ci/abstractions-public-build.yml
    - eng/ci/templates/jobs/test-abstractions.yml
    - eng/ci/templates/steps/build-abstractions.yml

pr:
  branches:
    include:
    - main
    - vnext
    - feature/*
  paths:
    include:
    - src/Func.Cli.Abstractions/**
    - eng/ci/abstractions-public-build.yml
    - eng/ci/templates/jobs/test-abstractions.yml
    - eng/ci/templates/steps/build-abstractions.yml

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    settings:
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}
      networkIsolationPolicy: Preferred, GitHub, NuGet

    stages:
      - stage: Build
        displayName: 'Build Abstractions'
        jobs:
        - template: /eng/ci/templates/jobs/test-abstractions.yml@self
          parameters:
            name: Windows
            pool:
              name: 1es-pool-azfunc-public
              image: 1es-windows-2022
              os: windows
        - template: /eng/ci/templates/jobs/test-abstractions.yml@self
          parameters:
            name: Linux
            pool:
              name: 1es-pool-azfunc-public
              image: 1es-ubuntu-24.04-min
              os: linux
