schedules:
- cron: "30 2 * * *"
  displayName: Nightly Consolidation
  always: true
  branches:
    include:
      - main

name: $(Build.SourceBranchName)_$(Build.Reason)

trigger: none

# This pipeline is triggered by the completion of builds
# in the core-tools-inproc and core-tools-default pipelines
resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release
  pipelines:
    - pipeline: core-tools-host
      source: azure/azure-functions-core-tools/core-tools-host.official

    # For regular builds (non-nightly)
    - pipeline: core-tools-inproc
      source: azure/azure-functions-core-tools/core-tools.official
      branch: in-proc
      trigger:
        branches:
          include:
            - in-proc

    - pipeline: core-tools-default
      source: azure/azure-functions-core-tools/core-tools.official
      branch: main
      trigger:
        branches:
          include:
            - main

    # For nightly builds only
    - pipeline: core-tools-inproc-nightly
      source: azure/azure-functions-core-tools/core-tools.official
      branch: in-proc
      tags:
        - nightly-build  # Only select runs with this tag
      trigger:
        branches:
          include:
            - in-proc
        tags:
          include:
            - nightly-build  # Only trigger on nightly builds
            
    - pipeline: core-tools-default-nightly
      source: azure/azure-functions-core-tools/core-tools.official
      branch: main
      tags:
        - nightly-build  # Only select runs with this tag
      trigger:
        branches:
          include:
            - main
        tags:
          include:
            - nightly-build  # Only trigger on nightly builds

variables:
- template: /ci/variables/cfs.yml@eng
- name: archs
  value: 'win-x64,win-x86,min.win-x64,osx-x64,linux-x64,osx-arm64,win-arm64,min.win-arm64,min.win-x86'
- name: isNightlyBuild
  value: $[eq(variables['Build.Reason'], 'Schedule')]

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    featureFlags:
      incrementalSDLBinaryAnalysis: true
      incrementalSDLSourceAnalysis: true
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true

    stages:
    - stage: ConsolidateArticacts
      displayName: "Assemble Artifacts"
      jobs:
      - template: /eng/ci/templates/official/jobs/process-nuget-package.yml@self
        parameters:
          jobDisplayName: $[ variables['isNightlyBuild'] && 'Nightly Package Processing' || 'Package Processing' ]

      - ${{ each arch in split(variables.archs,',') }}:
        - template: /eng/ci/templates/official/jobs/assemble-artifacts.yml@self
          parameters:
            arch: ${{ arch }}
            displayName: ${{ replace(replace(arch, '-', ''), '.', '') }}
            isNightlyBuild: $(isNightlyBuild)