schedules:
- cron: "30 2 * * *"
  displayName: Nightly Consolidation
  always: true
  branches:
    include:
      - main

name: $(Build.SourceBranchName)_$(Build.Reason)

trigger: none

# This pipeline is triggered by the completion of scheduled builds
# in the core-tools-inproc and core-tools-default pipelines
resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release
  pipelines:
    - pipeline: core-tools-host
      source: azure\azure-functions-core-tools\core-tools-host.official

    - pipeline: core-tools-inproc
      source: azure\azure-functions-core-tools\core-tools.official
      branch: in-proc  # in-proc branch of core-tools.official
      tags:
      - nightly-build
      trigger: 
        branches:
          include:
            - in-proc

    - pipeline: core-tools-default
      source: azure\azure-functions-core-tools\core-tools.official
      branch: main  # main branch of core-tools.official
      tags:
      - nightly-build
      trigger:
        branches:
          include:
            - main

variables:
- template: /ci/variables/cfs.yml@eng
- name: archs
  value:
  - { arch: 'win-x64', displayName: 'winx64' }
  - { arch: 'win-x86', displayName: 'winx86' }
  - { arch: 'min.win-x64', displayName: 'minwinx64' }
  - { arch: 'osx-x64', displayName: 'osx64' }
  - { arch: 'linux-x64', displayName: 'linuxx64' }
  - { arch: 'osx-arm64', displayName: 'osxarm64' }
  - { arch: 'win-arm64', displayName: 'winarm64' }
  - { arch: 'min.win-arm64', displayName: 'minwinarm64' }
  - { arch: 'min.win-x86', displayName: 'minwinx86' }

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    featureFlags:
      incrementalSDLBinaryAnalysis: true
      incrementalSDLSourceAnalysis: true
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
     
    stages:
    - stage: ConsolidateArticacts
      displayName: "Assemble Artifacts"
      jobs:
      - template: /eng/ci/templates/official/jobs/process-nuget-package.yml@self
      
      - ${{ each config in variables.archs }}:
        - template: /eng/ci/templates/official/jobs/assemble-artifacts.yml@self
          parameters:
            arch: ${{ config.arch }}
            displayName: ${{ config.displayName }}