schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - main
  always: true

pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - /src/CoreToolsHost/**

resources:
  repositories:
    - repository: 1es
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
    - repository: eng
      type: git
      name: engineering
      ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng
  - name: DisableKubernetesDeploymentDetector
    value: true

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    stages:
      - stage: BuildCoreToolsHost
        jobs:
        - template: /eng/ci/templates/official/jobs/host-build-pack.yml@self

      - stage: Merge
        dependsOn: 'BuildCoreToolsHost'

        jobs:
        - job: MergeArtifacts
          displayName: 'Merge artifacts'

          templateContext:
            type: artifactJob

            inputs:
              - input: pipelineArtifact
                artifactName: func-host-windows-signed
                targetPath: $(Build.ArtifactStagingDirectory)/func-cli-host/windows

              - input: pipelineArtifact
                artifactName: func-host-linux-signed
                targetPath: $(Build.ArtifactStagingDirectory)/func-cli-host/linux

            outputs:
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)/func-cli-host
                artifactName: 'func-cli-host'

      - stage: UploadToNightlyFeed
        dependsOn: 'Merge'
        condition: and(succeeded(), eq(variables['Build.Reason'], 'schedule'))

        jobs:
        - template: /eng/ci/templates/official/jobs/upload-artifact-to-feed.yml@self
          parameters:
            artifactName: 'func-cli-host'
            packageName: 'func-cli-host'
