schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - in-proc
  always: true

name: $(Build.SourceBranchName)_$(Build.Reason)

pr: none

trigger:
  branches:
    include:
    - release_4.0
    - in-proc

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    stages:
      - stage: BuildAndTest
        jobs:
          - template: /eng/ci/templates/official/jobs/build-test.yml@self
            parameters:
              artifactTargetFramework: inproc6
              jobTitle: BuildInproc6
          - template: /eng/ci/templates/official/jobs/build-test.yml@self
            parameters:
              artifactTargetFramework: inproc8
              jobTitle: BuildInproc8

      - stage: Merge
        dependsOn: 'BuildAndTest'

        jobs:
        - job: MergeArtifacts
          displayName: 'Merge artifacts'

          templateContext:
            type: artifactJob

            inputs:
              - input: pipelineArtifact
                artifactName: func-cli-inproc6
                targetPath: $(Build.ArtifactStagingDirectory)/func-cli-inproc/inproc6

              - input: pipelineArtifact
                artifactName: func-cli-inproc8
                targetPath: $Build.ArtifactStagingDirectory)/func-cli-inproc/inproc8

            outputs:
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectorye)/func-cli-inproc
                artifactName: 'func-cli-inproc'

      - stage: UploadToNightlyFeed
        dependsOn: 'Merge'
        condition: and(succeeded(), eq(variables['Build.Reason'], 'schedule'))

        jobs:
        - template: /eng/ci/templates/official/jobs/upload-artifact-to-feed.yml@self
          parameters:
            artifactName: 'func-cli-inproc'
            packageName: 'func-cli-inproc'
