schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - main
  always: true

pr: none

trigger:
  branches:
    include:
    - release_4.0
    - main
    - in-proc
    - feature/*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: /ci/variables/cfs.yml@eng
  - name: DisableKubernetesDeploymentDetector
    value: true
  - name: supportedRuntimes
    value: 'linux-x64,linux-arm64,osx-x64,osx-arm64,win-arm64,win-x64,win-x86,min.win-arm64,min.win-x86,min.win-x64'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    stages:
      - stage: BuildAndPublish
        jobs:
        - ${{ each runtime in split(variables.supportedRuntimes,',') }}:
          - template: /eng/ci/templates/official/jobs/publish-cli.yml@self
            parameters:
              runtime: ${{ runtime }}
              jobNameSuffix: ${{ replace(replace(runtime, '-', ''), '.', '') }}

        - template: /eng/ci/templates/official/jobs/pack-cli.yml@self

      - stage: Merge
        dependsOn: 'BuildAndPublish'

        jobs:
        - template: /eng/ci/templates/official/jobs/merge-pipeline-artifacts.yml@self

      - stage: UploadToNightlyFeed
        dependsOn: 'Merge'
        condition: and(succeeded(), eq(variables['Build.Reason'], 'schedule'))

        jobs:
        - template: /eng/ci/templates/official/jobs/upload-artifact-to-feed.yml@self
          parameters:
            artifactName: 'func-cli'
            packageName: 'func-cli'

      # Test Stages
      - stage: E2ETestWindows
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-windows.yml@self

      - stage: E2ETestLinux
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-linux.yml@self

      - stage: E2ETestOSX
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-osx.yml@self