parameters:
- name: sign
  type: boolean
  default: false

schedules:
- cron: "0 8 * * *"   # 12am PST
  displayName: Nightly Build
  branches:
    include:
      - main
      - vnext
  always: true

pr: none

trigger:
  branches:
    include:
    - main
    - vnext
    - feature/*
    - release/*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
- template: /ci/variables/cfs.yml@eng
- name: sign
  readonly: true
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    value: true
  ${{ else }}:
    value: ${{ parameters.sign }}

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc
      image: 1es-ubuntu-24.04-min
      os: linux
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low

    sdl:
      codeql:
         runSourceLanguagesInSourceAnalysis: true

    stages:
      - stage: Build
        jobs:
        - template: /eng/ci/templates/jobs/build.yml@self
          parameters:
            sign: ${{ variables.sign }}
