schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - main
  always: true

trigger: none

pr:
  branches:
    include:
    - release_4.0
    - main
    - in-proc
  paths:
    include:
    - eng
    - src
    - test
    exclude:
    - docs
    - '**/*.md'

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - name: supportedRuntimes
    value: 'linux-x64,linux-arm64,osx-x64,osx-arm64,win-arm64,win-x64,win-x86,min.win-arm64,min.win-x86,min.win-x64'

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
      ${{ if eq( variables['Build.Reason'], 'Schedule' ) }}:
        demands:
        - Priority -equals Low
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}
    stages:
      - stage: Build

        jobs:
        - ${{ each runtime in split(variables.supportedRuntimes,',') }}:
          - template: /eng/ci/templates/public/jobs/build-cli.yml@self
            parameters:
              runtime: ${{ runtime }}
              jobNameSuffix: ${{ replace(replace(runtime, '-', ''), '.', '') }}

      - stage: UnitTest
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/public/jobs/test-unit-windows.yml@self
        - template: /eng/ci/templates/public/jobs/test-unit-linux.yml@self

      # Do we want the E2E tests for the public build?
      # Might need this at first whilst we work on building out solid unit tests
      # - stage: E2ETestWindows
      #   dependsOn: ''

      #   jobs:
      #   - template: /eng/ci/templates/jobs/test-e2e-windows.yml@self

      # - stage: E2ETestLinux
      #   dependsOn: ''

      #   jobs:
      #   - template: /eng/ci/templates/jobs/test-e2e-linux.yml@self

      - stage: E2ETestOSX
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-osx.yml@self
