schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - main
  always: true

pr:
  branches:
    include:
    - release_4.0
    - main
    - in-proc

trigger:
  batch: true
  branches:
    include:
    - release_4.0
    - main
    - in-proc
    - feature/*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}
    stages:
      - stage: Build

        jobs:
        - template: /eng/ci/templates/public/jobs/build-cli.yml@self

      - stage: UnitTest
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-unit-windows.yml@self
        - template: /eng/ci/templates/jobs/test-unit-linux.yml@self

      # Do we want the E2E tests for the public build?
      # Might need this at first whilst we work on building out solid unit tests
      - stage: E2ETestWindows
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-windows.yml@self

      - stage: E2ETestLinux
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-linux.yml@self

      - stage: E2ETestOSX
        dependsOn: ''

        jobs:
        - template: /eng/ci/templates/jobs/test-e2e-osx.yml@self

        # All these E2E tests are just testing x64 of each os - do we want to test them all?
        # not necessarily the E2E tests, build run `func` for each runtime?