schedules:
- cron: "0 0 * * *"
  displayName: Nightly Build
  branches:
    include:
      - main
  always: true

name: $(Build.SourceBranchName)_$(Build.Reason)

pr:
  branches:
    include:
    - release_4.0
    - main
    - in-proc
    - feature/*

trigger:
  batch: true
  branches:
    include:
    - release_4.0
    - main
    - in-proc
    - feature/*

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true
    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}
    stages:
      - stage: BuildAndTest
        jobs:
        - template: /eng/ci/templates/public/jobs/build-test-public.yml@self

