parameters:
- name: WorkloadProjectName
  type: string
- name: sign
  type: boolean
  default: false

jobs:
- job: build_workload_${{ parameters.WorkloadProjectName }}
  displayName: Build Workload.${{ parameters.WorkloadProjectName }}

  variables:
  - template: /eng/ci/templates/variables/build.yml@self
  - name: workload_project
    readonly: true
    value: src/Workload/Stacks/${{ parameters.WorkloadProjectName }}/Workload.${{ parameters.WorkloadProjectName }}.csproj
  - name: workload_tests
    readonly: true
    value: test/Workload/Stacks/${{ parameters.WorkloadProjectName }}.Tests/Workload.${{ parameters.WorkloadProjectName }}.Tests.csproj
  - name: pack_dir
    readonly: true
    value: $(Build.ArtifactStagingDirectory)/pkg

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish Workload Package
      path: $(pack_dir)
      artifact: drop_workload_${{ parameters.WorkloadProjectName }}

  steps:
    - template: /eng/ci/templates/steps/install-dotnet.yml@self

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: custom
        custom: restore
        projects: $(workload_tests)
        arguments: -v m

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: $(workload_tests)
        arguments: -c $(configuration) -v m --no-restore

    - task: DotNetCoreCLI@2
      displayName: Unit tests
      inputs:
        command: test
        projects: $(workload_tests)
        arguments: -c $(configuration) --no-build

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign workload assembly
          minimatch: true
          signType: dll-strong-name
          folderPath: out/bin/Workload.${{ parameters.WorkloadProjectName }}
          pattern: |
            **/Azure.Functions.Cli.Workload.${{ parameters.WorkloadProjectName }}.dll

    - task: DotNetCoreCLI@2
      displayName: Pack
      inputs:
        command: custom
        custom: pack
        projects: $(workload_project)
        arguments: -c $(configuration) -v m -o $(pack_dir) --no-build

    - ${{ if eq(parameters.sign, true) }}:
      - template: ci/sign-files.yml@eng
        parameters:
          displayName: Sign workload nupkg
          signType: nuget
          folderPath: $(pack_dir)
          pattern: '*.nupkg'
