jobs:
# Run E2E tests using CLI artifact from BuildAndPublish stage
- job: OSX_E2E_Test
  timeoutInMinutes: '60'
  displayName: 'E2E Test:'

  pool:
    name: Azure Pipelines
    image: macOS-latest
    os: macOS

  strategy:
    matrix:
      dotnetIsolated_osx_x64:
        languageWorker: 'DotnetIsolated'
        runtime: 'osx-x64'
      node_osx_x64:
        languageWorker: 'Node'
        runtime: 'osx-x64'
      powershell_osx_x64:
        languageWorker: 'Powershell'
        runtime: 'osx-x64'
      python_osx_x64:
        languageWorker: 'Python'
        runtime: 'osx-x64'
      custom_osx_x64:
        languageWorker: 'Custom'
        runtime: 'osx-x64'

  steps:
  - pwsh: ./eng/scripts/start-emulators.ps1
    displayName: 'Start emulators (NoWait)'

  - script: |
      brew install go
      go version
    displayName: 'Install Go'

  - script: |
      sudo chown -R $(id -u):$(id -g) ~/.npm
      npm install -g @azure/functions
    displayName: 'Install @azure/functions'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  # Download the signed CLI artifact from BuildAndPublish stage
  - task: DownloadPipelineArtifact@2
    displayName: 'Download CLI Artifact from Build'
    inputs:
      artifactName: 'func-cli-$(runtime)'
      targetPath: '$(Build.ArtifactStagingDirectory)/artifacts/$(runtime)'

  # Extract the CLI zip
  - bash: |
      cd $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)
      # Find and extract the CLI zip
      ZIP_FILE=$(ls Azure.Functions.Cli.$(runtime).*.zip 2>/dev/null | head -1)
      if [ -n "$ZIP_FILE" ]; then
        echo "Extracting $ZIP_FILE..."
        unzip -o "$ZIP_FILE"
        rm "$ZIP_FILE"
      fi
      chmod +x func gozip 2>/dev/null || true
      ls -la
    displayName: 'Extract and prepare CLI'

  # Cleanup temp directories before running tests
  - bash: |
      echo "Cleaning up temp directories..."
      rm -rf /tmp/func-e2e-* || true
      rm -rf ~/.azure-functions-core-tools/dotnet-templates-custom-hives || true
      df -h
    displayName: 'Cleanup temp directories'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)
      runtime: $(runtime)

  # Always cleanup after tests, even on failure
  - bash: |
      echo "Post-test cleanup..."
      rm -rf /tmp/func-e2e-* || true
      rm -rf ~/.azure-functions-core-tools/dotnet-templates-custom-hives || true
      df -h
    displayName: 'Post-test cleanup'
    condition: always()