jobs:
- job: Linux_E2E_Test
  timeoutInMinutes: '180'
  displayName: 'E2E Test:'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-ubuntu-22.04
    os: linux

  strategy:
    matrix:
      dotnetIsolated_linux_x64:
        languageWorker: 'DotnetIsolated'
        runtime: 'linux-x64'
      node_linux_x64:
        languageWorker: 'Node'
        runtime: 'linux-x64'
      powershell_linux_x64:
        languageWorker: 'Powershell'
        runtime: 'linux-x64'
      python_linux_x64:
        languageWorker: 'Python'
        runtime: 'linux-x64'

  steps:
  - pwsh: ./eng/scripts/start-emulators.ps1
    displayName: 'Start emulators (NoWait)'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - pwsh: |
      dotnet publish src/Cli/func/Azure.Functions.Cli.csproj `
        -c Release `
        -f net8.0 `
        -r $(runtime) `
        --self-contained `
        -o $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)
    displayName: 'Publish CLI ($(runtime))'

  - bash: |
      chmod +x $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)/func
      chmod +x $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)/gozip
    displayName: 'Make CLI binaries executable'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)
      runtime: $(runtime)
