jobs:
- job: Windows_E2E_Test
  timeoutInMinutes: '180'
  displayName: 'E2E Test:'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  # Need to find an arm64 image/agent for windows
  strategy:
    matrix:
      dotnet_win_x64:
        languageWorker: 'Dotnet'
        runtime: 'win-x64'
      # dotnet_win_arm64:
      #   languageWorker: 'Dotnet'
      #   runtime: 'win-arm64'

      dotnetIsolated_win_x64:
        languageWorker: 'DotnetIsolated'
        runtime: 'win-x64'
      # dotnetIsolated_win_arm64:
      #   languageWorker: 'DotnetIsolated'
      #   runtime: 'win-arm64'

      node_win_x64:
        languageWorker: 'Node'
        runtime: 'win-x64'
      # node_win_arm64:
      #   languageWorker: 'Node'
      #   runtime: 'win-arm64'

      powershell_win_x64:
        languageWorker: 'Powershell'
        runtime: 'win-x64'
      # powershell_win_arm64:
      #   languageWorker: 'Powershell'
      #   runtime: 'win-arm64'


  steps:
  - pwsh: ./eng/scripts/start-emulators.ps1 -NoWait
    displayName: 'Start emulators (NoWait)'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - pwsh: |
      dotnet publish src/Cli/func/Azure.Functions.Cli.csproj `
      -c Release `
      -f net8.0 `
      -r $(runtime) `
      --self-contained `
      -o $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)
    displayName: 'Publish CLI ($(runtime))'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)
      runtime: $(runtime)