parameters:
# When true, build CLI inline instead of downloading from a previous stage
# Use for public/PR builds where we want fast parallel execution
- name: buildCliInline
  type: boolean
  default: false

# Artifact name to download (only used when buildCliInline is false)
# Official builds use 'func-cli-linux-x64', public builds use 'e2e-cli-linux-x64'
- name: artifactName
  type: string
  default: 'func-cli-linux-x64'

jobs:
# Build CLI job (only when buildCliInline is true)
- ${{ if eq(parameters.buildCliInline, true) }}:
  - job: Build_Linux_CLI
    timeoutInMinutes: '10'
    displayName: 'Build CLI (linux-x64)'

    pool:
      name: 1es-pool-azfunc-public
      image: 1es-ubuntu-24.04-min
      os: linux

    steps:
    - task: UseDotNet@2
      displayName: Install .NET SDK from global.json
      inputs:
        packageType: sdk
        useGlobalJson: true

    - bash: |
        sudo apt-get update
        sudo apt-get install -y golang
        go version
      displayName: 'Install Go'

    - pwsh: |
        dotnet publish src/Cli/func/Azure.Functions.Cli.csproj `
          -c Release `
          -f net8.0 `
          -r linux-x64 `
          --self-contained `
          -o $(Build.ArtifactStagingDirectory)/artifacts/linux-x64
      displayName: 'Publish CLI (linux-x64)'

    - bash: |
        chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/func
        chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/gozip
      displayName: 'Make CLI binaries executable'

    - task: 1ES.PublishPipelineArtifact@1
      displayName: 'Publish CLI Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/artifacts/linux-x64'
        artifactName: 'e2e-cli-linux-x64'

# Run E2E tests
- job: Linux_E2E_Test
  ${{ if eq(parameters.buildCliInline, true) }}:
    dependsOn: Build_Linux_CLI
  timeoutInMinutes: '40'
  displayName: 'E2E Test:'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-ubuntu-24.04-min
    os: linux

  strategy:
    matrix:
      dotnetIsolated_linux_x64:
        languageWorker: 'DotnetIsolated'
        runtime: 'linux-x64'
      node_linux_x64:
        languageWorker: 'Node'
        runtime: 'linux-x64'
      powershell_linux_x64:
        languageWorker: 'Powershell'
        runtime: 'linux-x64'
      python_linux_x64:
        languageWorker: 'Python'
        runtime: 'linux-x64'
      custom_linux_x64:
        languageWorker: 'Custom'
        runtime: 'linux-x64'

  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install -y npm
    displayName: 'Install npm'

  - pwsh: ./eng/scripts/start-emulators.ps1
    displayName: 'Start emulators (NoWait)'

  - template: /eng/ci/templates/steps/install-e2e-tools.yml@self
    parameters:
      worker: $(languageWorker)

  # Download CLI artifact (when NOT building inline - official builds)
  - ${{ if eq(parameters.buildCliInline, false) }}:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download CLI Artifact from Build'
      inputs:
        artifactName: '${{ parameters.artifactName }}'
        targetPath: '$(Build.ArtifactStagingDirectory)/artifacts/$(runtime)'

    - bash: |
        cd $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)
        # Find and extract the CLI zip
        ZIP_FILE=$(ls Azure.Functions.Cli.$(runtime).*.zip 2>/dev/null | head -1)
        if [ -n "$ZIP_FILE" ]; then
          echo "Extracting $ZIP_FILE..."
          unzip -o "$ZIP_FILE"
          rm "$ZIP_FILE"
        fi
        chmod +x func gozip 2>/dev/null || true
        ls -la
      displayName: 'Extract and prepare CLI'

  # Download CLI artifact (when building inline - public builds)
  - ${{ if eq(parameters.buildCliInline, true) }}:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download CLI Artifact'
      inputs:
        artifactName: 'e2e-cli-linux-x64'
        targetPath: '$(Build.ArtifactStagingDirectory)/artifacts/$(runtime)'

    - bash: |
        chmod +x $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)/func
        chmod +x $(Build.ArtifactStagingDirectory)/artifacts/$(runtime)/gozip
      displayName: 'Make CLI binaries executable'

  # Cleanup temp directories before running tests
  - bash: |
      echo "Cleaning up temp directories..."
      rm -rf /tmp/func-e2e-* || true
      rm -rf ~/.azure-functions-core-tools/dotnet-templates-custom-hives || true
      df -h
    displayName: 'Cleanup temp directories'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)
      runtime: $(runtime)

  # Always cleanup after tests, even on failure
  - bash: |
      echo "Post-test cleanup..."
      rm -rf /tmp/func-e2e-* || true
      rm -rf ~/.azure-functions-core-tools/dotnet-templates-custom-hives || true
      df -h
    displayName: 'Post-test cleanup'
    condition: always()
