parameters:
  - name: name
    type: string
  - name: pool
    type: object

jobs:
- job: Build_${{ parameters.name }}
  displayName: 'Build: ${{ parameters.name }}'
  timeoutInMinutes: 30

  pool: ${{ parameters.pool }}

  steps:
  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - template: /eng/ci/templates/steps/build-abstractions.yml@self
