jobs:
# Run E2E tests using CLI artifact from BuildAndPublish stage
- job: Windows_E2E_Test
  timeoutInMinutes: '60'
  displayName: 'E2E Test:'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  strategy:
    matrix:
      dotnetIsolated_win_x64:
        languageWorker: 'DotnetIsolated'
        runtime: 'win-x64'
      node_win_x64:
        languageWorker: 'Node'
        runtime: 'win-x64'
      powershell_win_x64:
        languageWorker: 'Powershell'
        runtime: 'win-x64'
      python_win_x64:
        languageWorker: 'Python'
        runtime: 'win-x64'
      custom_win_x64:
        languageWorker: 'Custom'
        runtime: 'win-x64'

  steps:
  - pwsh: ./eng/scripts/start-emulators.ps1 -NoWait
    displayName: 'Start emulators (NoWait)'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  # Download the signed CLI artifact from BuildAndPublish stage
  - task: DownloadPipelineArtifact@2
    displayName: 'Download CLI Artifact from Build'
    inputs:
      artifactName: 'func-cli-$(runtime)'
      targetPath: '$(Build.ArtifactStagingDirectory)/artifacts/$(runtime)'

  # Extract the CLI zip
  - pwsh: |
      $artifactPath = "$(Build.ArtifactStagingDirectory)/artifacts/$(runtime)"
      Set-Location $artifactPath
      # Find and extract the CLI zip
      $zipFile = Get-ChildItem -Filter "Azure.Functions.Cli.$(runtime).*.zip" | Select-Object -First 1
      if ($zipFile) {
        Write-Host "Extracting $($zipFile.Name)..."
        Expand-Archive -Path $zipFile.FullName -DestinationPath . -Force
        Remove-Item $zipFile.FullName
      }
      Get-ChildItem
    displayName: 'Extract and prepare CLI'

  # Cleanup temp directories before running tests
  - pwsh: |
      Write-Host "Cleaning up temp directories..."
      Remove-Item -Path "$env:TEMP\func-e2e-*" -Recurse -Force -ErrorAction SilentlyContinue
      $hivePath = Join-Path $env:LOCALAPPDATA "azure-functions-core-tools\dotnet-templates-custom-hives"
      if (Test-Path $hivePath) {
        Remove-Item -Path $hivePath -Recurse -Force -ErrorAction SilentlyContinue
      }
      Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{N='FreeGB';E={[math]::Round($_.Free/1GB,2)}}
    displayName: 'Cleanup temp directories'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)
      runtime: $(runtime)

  # Always cleanup after tests, even on failure
  - pwsh: |
      Write-Host "Post-test cleanup..."
      Remove-Item -Path "$env:TEMP\func-e2e-*" -Recurse -Force -ErrorAction SilentlyContinue
      $hivePath = Join-Path $env:LOCALAPPDATA "azure-functions-core-tools\dotnet-templates-custom-hives"
      if (Test-Path $hivePath) {
        Remove-Item -Path $hivePath -Recurse -Force -ErrorAction SilentlyContinue
      }
    displayName: 'Post-test cleanup'
    condition: always()