jobs:
- job: Linux_E2E_Test
  timeoutInMinutes: '180'
  displayName: 'E2E Test:'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-ubuntu-22.04
    os: linux

  strategy:
    matrix:
      dotnet:
        languageWorker: 'Dotnet'
      dotnetIsolated:
        languageWorker: 'DotnetIsolated'
      node:
        languageWorker: 'Node'
      powershell:
        languageWorker: 'Powershell'

  steps:
  - pwsh: ./eng/scripts/start-emulators.ps1 -NoWait
    displayName: 'Start emulators (NoWait)'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - pwsh: |
      dotnet publish src\Cli\func\Azure.Functions.Cli.csproj `
      -c Release `
      -f net8.0 `
      -r linux-x64 `
      --self-contained `
      -o $(Build.ArtifactStagingDirectory)/artifacts/linux-x64 `
      /p:CommitHash=$(Build.SourceVersion) `
      /p:IntegrationBuildNumber=$(Build.BuildNumber)
    displayName: 'Publish Cli for linux-x64'

  - bash: |
      echo "Making CLI binaries executable..."

      chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/func
      chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/gozip
      # chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/in-proc8/func
      # chmod +x $(Build.ArtifactStagingDirectory)/artifacts/linux-x64/in-proc6/func
    displayName: 'Make func-related binaries executable'

  - template: /eng/ci/templates/steps/run-e2e-tests.yml@self
    parameters:
      worker: $(languageWorker)