jobs:
- job: Build_CLI
  timeoutInMinutes: "180"

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  steps:
  - template: /eng/ci/templates/steps/install-tools.yml@self

  - pwsh: ./eng/scripts/validateWorkerVersions.ps1
    displayName: 'Validate worker versions'

  - pwsh: ./eng/scripts/check-vulnerabilities.ps1
    displayName: 'Check for security vulnerabilities'

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - template: /eng/ci/templates/steps/publish-cli.yml@self

  templateContext:
    outputs:
    - output: pipelineArtifact
      path: '$(Build.ArtifactStagingDirectory)/artifacts'
      artifact: FuncCli
