jobs:
- job: Build_CLI
  timeoutInMinutes: "180"

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  steps:
  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - pwsh: ./eng/scripts/validateWorkerVersions.ps1
    displayName: 'Validate worker versions'

  - pwsh: ./eng/scripts/check-vulnerabilities.ps1
    displayName: 'Check for security vulnerabilities'

  # Do we need to publish the CLI for the public build? Should we just build the .sln and publish one RID instead?
  # - template: /eng/ci/templates/steps/publish-cli.yml@self

  - pwsh: |
      dotnet publish src\Cli\func\Azure.Functions.Cli.csproj `
      -c Release `
      -f net8.0 `
      -r win-arm64 `
      --self-contained `
      -o $(Build.ArtifactStagingDirectory)/artifacts/win-arm64 `
      -p:ZipAfterPublish=true
    displayName: 'Publish CLI (win-arm64)'

  templateContext:
    outputs:
    - output: pipelineArtifact
      path: '$(Build.ArtifactStagingDirectory)/artifacts'
      artifact: func-cli
