parameters:
  - name: runtime
    type: string
  - name: jobNameSuffix
    type: string

jobs:
- job: Build_${{ parameters.jobNameSuffix }}
  displayName: 'Build ${{ parameters.runtime }}'
  timeoutInMinutes: "180"

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  steps:
  - task: UseDotNet@2
    displayName: Install .NET SDK from global.json
    inputs:
      packageType: sdk
      useGlobalJson: true

  - pwsh: ./eng/scripts/validate-worker-versions.ps1
    displayName: 'Validate worker versions'

  - pwsh: ./eng/scripts/check-vulnerabilities.ps1
    displayName: 'Check for security vulnerabilities'

  - pwsh: |
      $runtime = "${{ parameters.runtime }}"
      if ($runtime.StartsWith('min')) {
          $isMinified = '/p:IsMinified=true'
          $runtime = $runtime -replace '^min\.?', ''
      } else {
          $isMinified = ''
      }

      dotnet publish src/Cli/func/Azure.Functions.Cli.csproj `
        -o "$(Build.ArtifactStagingDirectory)/artifacts/$runtime" `
        -c Release `
        -f net8.0 `
        -r $runtime `
        --self-contained `
        /p:ZipAfterPublish=true `
        /p:ZipArtifactsPath="$(Build.ArtifactStagingDirectory)/artifacts-zipped" `
        $isMinified
    displayName: 'Build & Zip CLI'

  templateContext:
    outputs:
    - output: pipelineArtifact
      path: '$(Build.ArtifactStagingDirectory)/artifacts-zipped'
      artifact: func-cli-${{ parameters.runtime }}-$(Build.BuildId)_$(System.JobAttempt)