jobs:
- job: Default
  timeoutInMinutes: "180"
  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  variables:
    devops_buildNumber: $[counter(format(''), 1500)]
    DEVOPS_REPO_BRANCH: $[coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'])]
    DEVOPS_REPO_COMMIT: $(Build.SourceVersion)

  steps:
  - pwsh: . "eng/scripts/start-emulators.ps1" -NoWait
    displayName: "Start emulators (NoWait)"

  - pwsh: |
      $isIntegrationBuild = $false
      if ($env:INTEGRATIONBUILDNUMBER -like "PreRelease*-*")
      {
          $isIntegrationBuild = $true
      }
      Write-Host "##vso[task.setvariable variable=IsIntegrationBuild]$isIntegrationBuild"
      Write-Host "IsIntegrationBuild: $isIntegrationBuild"
    displayName: 'Set IsIntegrationBuild variable'

  - pwsh: |
      Write-Host "Target branch: '$(DEVOPS_REPO_BRANCH)'"
    displayName: Set up environment variables

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'

  - pwsh: |
      Import-Module "./eng/scripts/modules/pipelineUtilities.psm1" -Force
      Install-Dotnet
    displayName: 'Install .NET 6.0 and 3.1'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec:
    displayName: Install Nuget tool

  - pwsh: |
      eng/scripts/validateWorkerVersions.ps1
    displayName: 'Validate worker versions'
    condition: ne(variables['skipWorkerVersionValidation'], 'true')

  - pwsh: |
      eng/scripts/check-vulnerabilities.ps1
    displayName: "Check for security vulnerabilities"

  - pwsh: |
      eng/scripts/build.ps1
    env:
      BuildArtifactsStorage: $(BuildArtifactsStorage)
      IsReleaseBuild: false
      IsPublicBuild: true
      IsCodeqlBuild: false
    displayName: 'Executing build script'

  - task: 1ES.PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: 'D:/a/_work/1/s/test/Cli/Func.E2ETests/TestResults'
      artifactName: '*.trx'
      artifactType: 'pipeline'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'D:/a/_work/1/s/test/Cli/Func.E2ETests/TestResults/*.trx'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()

  templateContext:
    outputs:
    - output: pipelineArtifact
      path: 'out/bin/Azure.Functions.Cli.Tests/debug/ZippedOnWindows.zip'
      artifact: ZippedOnWindows

- job: Test_Linux
  timeoutInMinutes: "180"
  dependsOn: Default

  pool:
    name: 1es-pool-azfunc-public
    image: '1es-ubuntu-22.04'
    os: 'linux'

  steps:
  - download: current
    displayName: 'Download test zip'
    artifact: ZippedOnWindows

  - script: |
      sudo apt-get update
      sudo apt-get -y install fuse-zip
    displayName: 'Install fuse-zip'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/Azure.Functions.Cli.Tests.csproj'
      arguments: '--filter CreateZip_Succeeds'
    displayName: 'Run zip test'
