jobs:
- job: Windows_Unit_Test
  displayName: 'Unit Test: Windows'

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-windows-2022
    os: windows

  steps:
  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  # The windows part of ZipHelpers test will create a Zip file that we need to download and test on Linux.
  - template: /eng/ci/templates/public/steps/run-unit-tests.yml@self

  templateContext:
    outputs:
    - output: pipelineArtifact
      path: 'out/bin/Azure.Functions.Cli.UnitTests/debug/ZippedOnWindows.zip'
      artifact: ZippedOnWindows
