jobs:
- job: Linux_Unit_Test
  displayName: 'Unit Test: Linux'
  # One of the unit tests depends on downloading a zip file created by the Windows unit tests.
  dependsOn: Windows_Unit_Test

  pool:
    name: 1es-pool-azfunc-public
    image: 1es-ubuntu-22.04
    os: linux

  steps:
  - download: current
    displayName: 'Download windows test zip'
    artifact: ZippedOnWindows

  - script: |
      sudo apt-get update
      sudo apt-get -y install fuse-zip
    displayName: 'Install fuse-zip'

  - template: /eng/ci/templates/steps/install-tools.yml@self

  - template: /eng/ci/templates/steps/restore-nuget.yml@self

  - template: /eng/ci/templates/public/steps/run-unit-tests.yml@self