// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using System.Text;
using Azure.Functions.Cli.Tools.TemplateGenerator.Common;
using Azure.Functions.Cli.Tools.TemplateGenerator.Model;
using Azure.Functions.Cli.Tools.TemplateGenerator.V2.Model;

namespace Azure.Functions.Cli.Tools.TemplateGenerator.V2;

internal static class UserPromptsEmitterV2
{
    private const string PromptsNamespace = "Azure.Functions.Cli.UserPrompts";

    private const string PocoHeader = """
        // <auto-generated/>
        #nullable enable

        namespace Azure.Functions.Cli.UserPrompts;

        """;

    public static string EmitUserPrompt() => PocoHeader + """
        /// <summary>
        /// Represents a user prompt definition for the v2 templates programming model.
        /// </summary>
        internal sealed class UserPromptV2
        {
            /// <summary>Gets the prompt id (e.g. "httpTrigger-route").</summary>
            public required string Id { get; init; }

            /// <summary>Gets the prompt name (typically equal to <see cref="Id"/>).</summary>
            public required string Name { get; init; }

            /// <summary>Gets the value type expected for this prompt.</summary>
            public required UserPromptValueTypeV2 Value { get; init; }

            /// <summary>Gets the default value, if any. May be a string or bool.</summary>
            public object? DefaultValue { get; init; }

            /// <summary>Gets the localized label (often a token reference).</summary>
            public string? Label { get; init; }

            /// <summary>Gets the localized help text (often a token reference).</summary>
            public string? Help { get; init; }

            /// <summary>Gets the placeholder text shown in UI inputs, if any.</summary>
            public string? Placeholder { get; init; }

            /// <summary>Gets the resource picker hint, if any (e.g. "Storage", "DocumentDB").</summary>
            public string? Resource { get; init; }

            /// <summary>Gets the expected file extension when this prompt selects a filename.</summary>
            public string? FileExtension { get; init; }

            /// <summary>Gets validators applied to user input.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<UserPromptValidatorV2> Validators { get; init; }

            /// <summary>Gets the allowed enum values when <see cref="Value"/> is <see cref="UserPromptValueTypeV2.Enum"/>.</summary>
            public required global::System.Collections.Generic.IReadOnlyList<UserPromptEnumValueV2> Enum { get; init; }
        }

        """;

    public static string EmitValueType() => PocoHeader + """
        /// <summary>
        /// The expected value type for a v2 user prompt.
        /// </summary>
        internal enum UserPromptValueTypeV2
        {
            /// <summary>The prompt has no explicit value type (free-form input).</summary>
            None,

            /// <summary>String input.</summary>
            String,

            /// <summary>Boolean input.</summary>
            Bool,

            /// <summary>Single selection from <see cref="UserPromptV2.Enum"/>.</summary>
            Enum,
        }

        """;

    public static string EmitValidator() => PocoHeader + """
        /// <summary>
        /// A regex validator applied to a v2 user prompt input.
        /// </summary>
        internal sealed class UserPromptValidatorV2
        {
            /// <summary>Gets the regular expression that valid input must match.</summary>
            public required string Expression { get; init; }

            /// <summary>Gets the error text shown when input does not match (often a token reference).</summary>
            public required string ErrorText { get; init; }
        }

        """;

    public static string EmitEnumValue() => PocoHeader + """
        /// <summary>
        /// A single allowed value for a v2 user prompt of <see cref="UserPromptValueTypeV2.Enum"/>.
        /// </summary>
        internal sealed class UserPromptEnumValueV2
        {
            /// <summary>Gets the underlying value emitted to the prompt response.</summary>
            public required string Value { get; init; }

            /// <summary>Gets the localized display name shown in UI (often a token reference).</summary>
            public required string Display { get; init; }
        }

        """;

    public static IEnumerable<(string HintName, string Source)> EmitStaticData(UserPromptsCatalogModelV2 catalog)
    {
        foreach (UserPromptModelV2 prompt in catalog.Prompts)
        {
            var sb = new StringBuilder(2048);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownUserPrompts");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class V2");
            sb.AppendLine("    {");

            string fieldName = EmitterHelpers.KebabToPascal(prompt.Id);
            sb.Append("        public static readonly UserPromptV2 ").Append(fieldName).AppendLine(" =");
            EmitPrompt(sb, prompt, 3);
            sb.AppendLine(";");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            yield return ("KnownUserPrompts.V2." + fieldName + ".g.cs", sb.ToString());
        }

        {
            var sb = new StringBuilder(2048);
            AppendHeader(sb);
            sb.AppendLine("internal static partial class KnownUserPrompts");
            sb.AppendLine("{");
            sb.AppendLine("    internal static partial class V2");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly global::System.Collections.Generic.IReadOnlyDictionary<string, UserPromptV2> All =");
            sb.AppendLine("            new global::System.Collections.Generic.Dictionary<string, UserPromptV2>");
            sb.AppendLine("            {");
            foreach (UserPromptModelV2 prompt in catalog.Prompts)
            {
                string fieldName = EmitterHelpers.KebabToPascal(prompt.Id);
                sb.Append("                [").Append(EmitterHelpers.Literal(prompt.Id)).Append("] = ").Append(fieldName).AppendLine(",");
            }

            sb.AppendLine("            };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            yield return ("KnownUserPrompts.V2.g.cs", sb.ToString());
        }
    }

    private static void AppendHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.Append("namespace ").Append(PromptsNamespace).AppendLine(";");
        sb.AppendLine();
    }

    private static void EmitPrompt(StringBuilder sb, UserPromptModelV2 prompt, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);
        string inner = EmitterHelpers.Indent(depth + 1);

        sb.Append(indent).AppendLine("new UserPromptV2");
        sb.Append(indent).AppendLine("{");
        AppendString(sb, inner, "Id", prompt.Id);
        AppendString(sb, inner, "Name", prompt.Name);
        sb.Append(inner).Append("Value = UserPromptValueTypeV2.").Append(prompt.Value switch
        {
            UserPromptValueKindV2.None => "None",
            UserPromptValueKindV2.String => "String",
            UserPromptValueKindV2.Bool => "Bool",
            UserPromptValueKindV2.Enum => "Enum",
            _ => "None",
        }).AppendLine(",");

        if (prompt.DefaultValue is not null)
        {
            sb.Append(inner).Append("DefaultValue = ");
            EmitDefaultValue(sb, prompt.DefaultValue);
            sb.AppendLine(",");
        }

        AppendOptionalString(sb, inner, "Label", prompt.Label);
        AppendOptionalString(sb, inner, "Help", prompt.Help);
        AppendOptionalString(sb, inner, "Placeholder", prompt.Placeholder);
        AppendOptionalString(sb, inner, "Resource", prompt.Resource);
        AppendOptionalString(sb, inner, "FileExtension", prompt.FileExtension);
        EmitValidators(sb, prompt.Validators, depth + 1);
        EmitEnumValues(sb, prompt.Enum, depth + 1);

        sb.Append(indent).Append('}');
    }

    private static void EmitDefaultValue(StringBuilder sb, UserPromptDefaultValueModelV2 value)
    {
        switch (value.Kind)
        {
            case UserPromptDefaultValueKindV2.String:
                sb.Append(value.StringValue is null ? "null" : EmitterHelpers.Literal(value.StringValue));
                break;
            case UserPromptDefaultValueKindV2.Bool:
                sb.Append(value.BoolValue == true ? "true" : "false");
                break;
            default:
                sb.Append("null");
                break;
        }
    }

    private static void EmitValidators(StringBuilder sb, EquatableArray<UserPromptValidatorModelV2> validators, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (validators.Length == 0)
        {
            sb.Append(indent).AppendLine("Validators = [],");
            return;
        }

        sb.Append(indent).AppendLine("Validators =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (UserPromptValidatorModelV2 v in validators)
        {
            sb.Append(inner).Append("new UserPromptValidatorV2 { Expression = ").Append(EmitterHelpers.Literal(v.Expression))
                .Append(", ErrorText = ").Append(EmitterHelpers.Literal(v.ErrorText)).AppendLine(" },");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void EmitEnumValues(StringBuilder sb, EquatableArray<UserPromptEnumValueModelV2> values, int depth)
    {
        string indent = EmitterHelpers.Indent(depth);

        if (values.Length == 0)
        {
            sb.Append(indent).AppendLine("Enum = [],");
            return;
        }

        sb.Append(indent).AppendLine("Enum =");
        sb.Append(indent).AppendLine("[");
        string inner = EmitterHelpers.Indent(depth + 1);
        foreach (UserPromptEnumValueModelV2 v in values)
        {
            sb.Append(inner).Append("new UserPromptEnumValueV2 { Value = ").Append(EmitterHelpers.Literal(v.Value))
                .Append(", Display = ").Append(EmitterHelpers.Literal(v.Display)).AppendLine(" },");
        }

        sb.Append(indent).AppendLine("],");
    }

    private static void AppendString(StringBuilder sb, string indent, string name, string value)
    {
        sb.Append(indent).Append(name).Append(" = ").Append(EmitterHelpers.Literal(value)).AppendLine(",");
    }

    private static void AppendOptionalString(StringBuilder sb, string indent, string name, string? value)
    {
        if (value is not null)
        {
            AppendString(sb, indent, name, value);
        }
    }
}
